### ISSUE TITLE
hom7-rtc-janus no access to Janus Demos

### ISSUE THREAD

**Issue by BillSegate** [sipcapture/homer7-docker#100]
Hi community!
I'm new using stuff like that, but i'm trying to understand a bit more.
I want to use the hom7-rtc-janus to see some demos, to understand how it work and to implement in my scenario.
I was watching that youtube video: https://www.youtube.com/watch?v=auutg9cou4I&t=769s&ab_channel=Meetecho.

So i have few questions about, Why when i'm setting up the docker-compose it says that the config variable is not set?

> ![image](https://user-images.githubusercontent.com/45166159/114153992-39a43c80-9920-11eb-8fc7-6b3dc80ec287.png)

what am i suppose to do?

The second question is: when everything is done, I tried to get into Janus Demos following that file: https://github.com/sipcapture/homer7-docker/blob/master/hepop/hom7-rtc-janus/README.md , but whenever I surf to MYSERVERIP:8080 it gives me "Connection denied".

Do i miss something? maybe changing something in the config files?

if you help me i'll appreciate it.

(and sorry for stupid questions)

EDIT: i have only access to Grafana ( MYSERVERIP:3000 )

**Comment by lmangani** [comment]
Hi @BillSegate those presentations are a bit outdated, in the latest docker containers HOMER is served on port 9080 - that's where you should start. If you can describe more what you're trying to achieve and what you're using in your scenario, I'd be happy to share ideas and update a few examples.

**Comment by lmangani** [comment]
@BillSegate my bad the link you used is for a HEADLESS homer, so Grafana is the only interface to the data ;)

**Comment by BillSegate** [comment]
@lmangani thank you for your fast answer! What should I do to populate the databases to see stats in grafana?

**Comment by lmangani** [comment]
I have no idea what your setup is - this demo is designed to capture Janus events and store them into Loki as well as timeseries for streams extracted from Janus event type 34

**Comment by lmangani** [comment]
@BillSegate did you manage to resolve? Happy to help you if more details are available
