### ISSUE TITLE
Service telegraf start failed

### ISSUE THREAD

**Issue by FengZStrong** [sipcapture/homer7-docker#105]
**docker-compose -v**
docker-compose version 1.29.2, build 5becea4c

**docker logs hom7-timescaledb-all_telegraf_1**
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found
/entrypoint.sh: exec: line 8: telegraf: not found

Any suggestion will be thankful!

**Comment by lmangani** [comment]
Hello @FengZStrong 
This is the container in question and it was indeed quite old: https://github.com/QXIP/telegraf-timescaledb
I've just pushed a new build with Telegraf 1.13.0 and the required patches, and it seems to run - please give it a try and let me know.
