### ISSUE TITLE
 No charts in qos-horaclifix

### ISSUE THREAD

**Issue by SerhiiZahuba** [sipcapture/homer7-docker#109]
I can't figure out this bug or something else. Help please, in Grafane there is no information on charts
qos-horaclifix

![image](https://user-images.githubusercontent.com/36307887/143928844-4ec70477-3e21-4e43-9569-62c2a6ed5bb0.png)

Thanks

**Comment by lmangani** [comment]
Hello @SerhiiZahuba 
Unless you're using horaclifix there is no data expected in those panels. 
This is really just an example but probably not relevant to your setup.
