### ISSUE TITLE
homer7-docker - grafana RTCP is empty

### ISSUE THREAD

**Issue by yu-boot** [sipcapture/homer7-docker#111]
Hello, I use Debian 10, 

docker-compose version 1.29.2, build 5becea4c

lastest homer7-docker package from this GIT

Homer shows itself SIP requests and statistics - OK. Grafana shows SOME SIP statistics, but RTCP dashboard is empty.

Grafana reports warnings and errors like this https://pastebin.com/sny5Gvth to console when I start docker package.

What can it be? How to make RTCP statistics work?

**Comment by lmangani** [comment]
Do you have RTCP data for any of your calls?

**Comment by lmangani** [comment]
I mean do you see it in HOMER? Please share an example or screenshot.
If there's no RTCP in the HOMER flow, there won't be any statistics either.

Are you using heplify to sniff the traffic or the Asterisk built in res_hep and res_hep_rtcp modules?

**Comment by yu-boot** [comment]
I use builtin HEP modules in Asterisk. Homer looks like this after a call on Asterisk
![image](https://user-images.githubusercontent.com/102296711/159943131-237703e8-4deb-44f0-a6a7-e68f27b65007.png)

I see something RTP-related on port 9060 on Docker machine, not only SIP messages, but I see nothing of this in Grafana. Calls and SIP methods are there, but RTCP etc contains "no data"

**Comment by lmangani** [comment]
Did you load the res_hep_rtcp module as well? https://github.com/sipcapture/homer/wiki/Examples:-Asterisk
Click the Call-id and a session popup will open. If there's any RTCP you will see it in the popup window.

**Comment by yu-boot** [comment]
I use very this hep.conf for Asterisk :)

I see something about RTP only here and only after clicking "Run query"
![image](https://user-images.githubusercontent.com/102296711/159948297-df4e2dd9-b648-44ff-873d-ca1a5754dd16.png)

**Comment by lmangani** [comment]
It seems you might be a new user. Please click the QoS tab. If there's any RTCP it will be shown in there.
If it is there, then it should be displayed in your statistics assuming prometheus is working right.

**Comment by yu-boot** [comment]
There are only packets and octets. Is this OK?
