### ISSUE TITLE
Logging for Docker containers should be limited

### ISSUE THREAD

**Issue by os11k** [sipcapture/homer7-docker#112]
I propose to limit size of log file what can be writen by docker for each container, something like these:

```
    logging:
      options:
        max-size: "50m"
```

Please let me know if these is ok and I will create pull request. We will limit each container to 50MB logs, otherwise containers might fill whole partition where it is located, what I personally think is not really desirable,

**Comment by khorsmann** [comment]
This issue should be closed since in master the Limit option is applied for all docker-compose.yml
