### ISSUE TITLE
 FATAL:  database "homer_config" does not exist

### ISSUE THREAD

**Issue by ultraboby** [sipcapture/homer7-docker#12]
Hi, The homer-webapp is not starting. I see this error after executing of docker-compose:

db_1              | 2019-02-19 12:31:38.558 UTC [48] FATAL:  database "homer_config" does not exist

**Comment by lmangani** [comment]
Hi @ultraboby please confirm which bundle you are attempting to run

**Comment by ultraboby** [comment]
hom7-hep-influx

**Comment by lmangani** [comment]
hepop or heplify-server?

**Comment by ultraboby** [comment]
homer7-docker/heplify-server/hom7-hep-influx

**Comment by ultraboby** [comment]
new error:

/api/v3/auth 503 (Service Unavailable)

**Comment by lmangani** [comment]
please attach the full container logs

**Comment by ultraboby** [comment]
run-parts: executing /docker-entrypoint.d/00-sed_files.sh
Pre-Flight provisioning completed!
run-parts: executing /docker-entrypoint.d/01-seeding_db.sh
Using environment: development
error: database "homer_config" does not exist
    at Connection.parseE (/app/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
Using environment: development
error: database "homer_config" does not exist
    at Connection.parseE (/app/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
Seeding completed!
run-parts: executing /docker-entrypoint.d/03-rebuild.sh

> homer-app@1.0.5 start /app
> node bootstrap.js

Server started
Debug: handler, error 
    {"msec":8.304310999810696,"error":"fail to get user: database \"homer_config\" does not exist","data":{"isBoom":true,"isServer":true,"output":{"statusCode":503,"payload":{"statusCode":503,"error":"Service Unavailable","message":"fail to get user: database \"homer_config\" does not exist"},"headers":{}}}}
Debug: handler, error 
    {"msec":7.198987999930978,"error":"fail to get user: database \"homer_config\" does not exist","data":{"isBoom":true,"isServer":true,"output":{"statusCode":503,"payload":{"statusCode":503,"error":"Service Unavailable","message":"fail to get user: database \"homer_config\" does not exist"},"headers":{}}}}
Debug: handler, error 
    {"msec":4.754692999878898,"error":"fail to get user: database \"homer_config\" does not exist","data":{"isBoom":true,"isServer":true,"output":{"statusCode":503,"payload":{"statusCode":503,"error":"Service Unavailable","message":"fail to get user: database \"homer_config\" does not exist"},"headers":{}}}}
Debug: handler, error 
    {"msec":2.1783330000471324,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"Not Found"},"headers":{}},"message":"Not Found"}}
Debug: handler, error 
    {"msec":1.3441210000310093,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"Not Found"},"headers":{}},"message":"Not Found"}}
Debug: handler, error 
    {"msec":1.7965379999950528,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"Not Found"},"headers":{}},"message":"Not Found"}}
Debug: handler, error 
    {"msec":3.1592870000749826,"error":"fail to get user: database \"homer_config\" does not exist","data":{"isBoom":true,"isServer":true,"output":{"statusCode":503,"payload":{"statusCode":503,"error":"Service Unavailable","message":"fail to get user: database \"homer_config\" does not exist"},"headers":{}}}}

**Comment by lmangani** [comment]
This would suggest the DB node is not ready when HEPlify-server starts and attempts creating the DB. Could you check out the logs for the `db` container and check for errors there?

**Comment by ultraboby** [comment]
2019-02-28 15:09:31.297 UTC [10843] FATAL:  database "homer_config" does not exist

**Comment by ultraboby** [comment]
init-user-db.sh scripit is wrong

**Comment by lmangani** [comment]
`init-user-db.sh` is not involved with creating database `homer_config`. Not sure what you mean by wrong, feel free to extend your explanation

**Comment by negbie** [comment]
@ultraboby please pull latest homer-app and heplify-server image from dockerhub. Since I had some problems with the knex migrations too I let heplify-server create the db's and tables too.

**Comment by ultraboby** [comment]
this is my init-user-db.sh script and the database is created:

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE DATABASE homer_config;
EOSQL

**Comment by negbie** [comment]
Thanks for the update but you don't even need a init-user-db.sh. heplify-server will try create all databases and tables for you and it will retry if the database is not ready.

**Comment by ultraboby** [comment]
This is the log from sipcapture/homer-app:master:

{"msec":4.4761160016059875,"error":"fail to get user: database \"homer_config\" does not exist","data":{"isBoom":true,"isServer":true,"output":{"statusCode":503,"payload":{"statusCode":503,"error":"Service Unavailable","message":"fail to get user: database \"homer_config\" does not exist"},"headers":{}}}}

**Comment by vandykew** [comment]
I'm getting the same issue  The web App starts, but when I go to login I get 

 2019-05-09 13:57:52.506 UTC [1201] FATAL:  database "homer_config" does not exist

And 


homer-webapp      |     {"msec":4.634887000080198,"error":"fail to get user: database \"homer_config\" does not exist","data":{"isBoom":true,"isServer":true,"output":{"statusCode":503,"payload":{"statusCode":503,"error":"Service Unavailable","message":"fail to get user: database \"homer_config\" does not exist"},"headers":{}}}}

**Comment by vandykew** [comment]
Also i am using 

hom7-hep-elastic

**Comment by ultraboby** [comment]
@vandykew Did you find a fix?

**Comment by lmangani** [comment]
ALL: please move to the 7.7. containers to make sure you are running supported code!
