### ISSUE TITLE
Logging doesn't work for loki

### ISSUE THREAD

**Issue by perrfect** [sipcapture/homer7-docker#122]
Hello.
Via docker-compose I've set up logging for loki max-size: "6144m":
```
 logging:
      options:
        max-size: "6144m"

```
But it is not working and now loki volume size is about 12Gb:
`72976e9f5038   grafana/loki             "/usr/bin/loki --con…"   0               11.8GB    2 weeks ago   Up 21 hours            loki`

**Comment by lmangani** [comment]
This doesn't seem related to our project. I would suggest referring to the Docker and Loki driver configuration.
