### ISSUE TITLE
Loki wal use big part of diskspace 

### ISSUE THREAD

**Issue by perrfect** [sipcapture/homer7-docker#123]
Hello.
Loki in docker-compose usages very intensively disk space.
Size per week about 20Gb.
Inside the loki docker container this space is used by directories:

/loki/wal
/tmp/loki/chunks

Which options in loki configs should I use for reducing the use of space on a disk or enable rotation for these directories?

**Comment by lmangani** [comment]
Hello @perrfect 
Loki is optional and literally duplicates all traffic - if you're not using it just disable it and drop the volumes. 
If you're using it for integrations, etc then refer to the loki configuration to adjust retention time.

Hope this helps!
