### ISSUE TITLE
Frontend result display is bugged

### ISSUE THREAD

**Issue by SebastianLuebke** [sipcapture/homer7-docker#125]
Hey,
im using hom7-prom-all docker-compose configuration and homer-web seems to be bugged. It doesnt matter what or in which time frame i filter i only get 200 results.

example:

time frame: today (00:00 - 23:59)
200 results
![Bildschirmfoto vom 2022-07-25 16-42-44](https://user-images.githubusercontent.com/21161532/180807487-26db885d-f966-446f-9192-faf52b0dac20.png)

time frame: today (10:00 - 11:00)
200 results
![Bildschirmfoto vom 2022-07-25 16-53-59](https://user-images.githubusercontent.com/21161532/180807638-7769966c-b7af-4a92-9702-8e009d3fdc12.png)

**Comment by lmangani** [comment]
@SebastianLuebke not a bug, its a feature. If you look you'll notice there is a `limit` query field which has a default of 200 when unset.

**Comment by SebastianLuebke** [comment]
lol thank you
