### ISSUE TITLE
LDAP authorization for homer and grafana in docker-compose

### ISSUE THREAD

**Issue by perrfect** [sipcapture/homer7-docker#126]
Hello.
Is it possible to enable LDAP authorization for homer and grafana in docker-compose?
And which parameters for docker-compose should I use?

**Comment by lmangani** [comment]
Hello @perrfect no the docker-compose doesn't include any variables for enabling LDAP so the options are:
1) create a PR to extend the entrypoint and config template behaviour
2) map your own custom JSON config with the desired settings off your filesystem

**Comment by perrfect** [comment]
> Hello @perrfect no the docker-compose doesn't include any variables for enabling LDAP so the options are:
> 
>     1. create a PR to extend the [entrypoint](https://github.com/sipcapture/homer-app/blob/master/docker/docker-entrypoint.d/1) and [config template](https://github.com/sipcapture/homer-app/blob/master/docker/webapp_config.json#L57) behaviour
> 
>     2. map your own custom JSON config with the desired settings off your filesystem

Hello. Thank you for your reply.
I've checked and seems parameters from the [endpoint](https://github.com/sipcapture/homer-app/blob/master/docker/docker-entrypoint.d/1) work fine.
But I didn't find how to create mapping for my LDAP groups and groups in homer.
Is it possible mapping separate groups for admins and users?

**Comment by lmangani** [comment]
perhaps @adubovikov and his team might have a suggestion here

**Comment by perrfect** [comment]
@adubovikov my LDAP config:

```
      - "AUTH_TYPE=ldap"
      - "LDAP_BASE=cn=users,cn=accounts,dc=ipa,dc=example,dc=com"
      - "LDAP_HOST=ipa-1.example.com"
      - "LDAP_PORT=636"
      - "LDAP_SSL=true"
      - "LDAP_SKIP_TLS=false"
      - "LDAP_SKIP_VERIFY=true"
      - "LDAP_ANONYMOUS=false"
      - "LDAP_BIND_DN=uid=homer,cn=users,cn=accounts,dc=ipa,dc=example,dc=com"
      - "LDAP_BIND_PASS=PASSWORD"
      - "LDAP_USER_FILTER=(uid=%s)"
      - 'LDAP_GROUP_FILTER=(\&(objectClass=posixgroup)(uid=%s))'
      - "LDAP_GROUP_ATTRIB=\"memberOf\""
      - "LDAP_ATTRIBUTES=\"uid\""
      - "LDAP_USER_DN=cn=users,cn=accounts,dc=ipa,dc=example,dc=com"
      - "LDAP_ADMINGROUP=homer_admins"
      - "LDAP_ADMINMODE=false"
      - "LDAP_USERGROUP=homer_users"
      - "LDAP_USERMODE=false"
```
But I can't login, because ADMINMODE and USERMODE are false.
When these modes are true I can login, but mapping groups in this case is ignoring.

I tried these options too, but result the same:
`- 'LDAP_USER_FILTER=(\&(uid=%s)(|(memberOf=cn=homer_admins,cn=groups,cn=accounts,dc=ipa,dc=example,dc=com)(memberOf=cn=homer_users,cn=groups,cn=accounts,dc=ipa,dc=example,dc=com)))'`

**Comment by lmangani** [comment]
@perrfect I would start by extending the template config with a variable for any fields you need to be configurable through ENV like you see for the other supported dynamic parameters, and then add it to the entrypoint. It's a copy-paste job using the examples already available - feel free to do a PR and we will correct if needed.

**Comment by perrfect** [comment]
> @perrfect I would start by extending the template config with a variable for any fields you need to be configurable through ENV like you see for the other supported dynamic parameters, and then add it to the entrypoint. It's a copy-paste job using the examples already available - feel free to do a PR and we will correct if needed.

First of all I need understand why LDAP group mapping not working and then create a PR, because now I have not full working LDAP configuration(

**Comment by lmangani** [comment]
Sure. Unfortunately we can't help with that part but feel free to share any observations.

**Comment by perrfect** [comment]
Works fine for FreeIPA in this configuration in docker-compose:

```
      - "AUTH_TYPE=ldap"
      - "LDAP_BASE=dc=ipa,dc=example,dc=com"
      - "LDAP_HOST=ipa-1.example.com"
      - "LDAP_PORT=636"
      - "LDAP_SSL=true"
      - "LDAP_SKIP_TLS=false"
      - "LDAP_SKIP_VERIFY=true"
      - "LDAP_ANONYMOUS=false"
      - "LDAP_BIND_DN=uid=homer,cn=users,cn=accounts,dc=ipa,dc=example,dc=com"
      - "LDAP_BIND_PASS=PASSWORD"
      - "LDAP_USER_FILTER=(\\&(objectClass=person)(uid=%s))"
      - "LDAP_GROUP_FILTER=(member=%s)"
      - "LDAP_USER_DN=uid=%s,cn=users,cn=accounts,dc=ipa,dc=example,dc=com"
      - "LDAP_ADMINGROUP=admin"
      - "LDAP_USERGROUP=sec_homer_users"
      - "LDAP_USERMODE=false"
      - "LDAP_ADMINMODE=false"
```

Still only the problem described in this issue [127](https://github.com/sipcapture/homer7-docker/issues/127)

Thank you.
This issue can close.
