### ISSUE TITLE
Bug in LDAP_GROUP_FILTER

### ISSUE THREAD

**Issue by perrfect** [sipcapture/homer7-docker#128]
Hello.
When I set **LDAP_GROUP_FILTER** to **(member=uid=%s)** username is not set and the filter is empty.
Logs from my FreeIPA server:

`[29/Jul/2022:15:07:47.866629112 +0200] conn=422609 op=4 SRCH base=“dc=ipa,dc=example,dc=com” scope=2` **filter="(member=uid=)"**` attrs=“cn memberOf groupattribute distinguishedName distinguishedName member”`

So mapping for LDAP groups is not working.

Could you fix it?

**Comment by adubovikov** [comment]
Probably, you have to escape % to set it available

**Comment by perrfect** [comment]
The problem is solved.
I mistakenly cut the LDAP_ATTRIBUTES from my configuration.
Thank you.
