### ISSUE TITLE
Source and destination IPs in Prometheus or Loki for Grafana

### ISSUE THREAD

**Issue by perrfect** [sipcapture/homer7-docker#129]
Hello.
Can, please, tell me is it possible find source of destination IP metrics in Prometheus or Loki and show it in Grafana?
In Homer I see these fields, but I need these metrics in Prometheus or Loki and further show in Grafana for counting the number of requests from different IPs.

**Comment by lmangani** [comment]
This is only possible by using Target alias tags for known IPs in the PROMTARGETIP array

```
      - "HEPLIFYSERVER_PROMTARGETIP=10.20.30.40"
      - "HEPLIFYSERVER_PROMTARGETNAME=local"
``
