### ISSUE TITLE
Homer 7 Installation and Configuration

### ISSUE THREAD

**Issue by jaco-iBez** [sipcapture/homer7-docker#13]
Hi guys

Can I maybe get some assistants, I'm trying to install homer in my Lab but for some reason I keep getting stuck. Does anyone maybe have a in-depth guide to install homer 7  and to configure it with a capture agent.

I want to setup a server for the capture agent that will capture the SIP and RTP streams from 4 different networks (each on a separate network port) and then i want to send that to another server on which Homer will run.

I tried installing homer 7 with the docker images, but i'm not seeing any VoIP traffic on homer. Some assistants regarding this will be awesome.

**Comment by negbie** [comment]
Hi @jaco-iBez,
first I would suggest to set in the docker-compose file
- "HEPLIFYSERVER_LOGLVL=info" to - "HEPLIFYSERVER_LOGLVL=debug"

So you can see HEP packets flowing into your server. Homer7 is pretty easy to setup with docker. I guess your issue is how to configure captagent properly. So I would suggest you to ask for help in the mailing list or in the captagent repo.

**Comment by jaco-iBez** [comment]
Hi @negbie 

Thank you, i will ask there also. The problem is that i play a pcap file from a CentOS server using ./heplify. I can than see the packets in the influxDB, but i can't see the calls in Homer.

I will ask in the mailinglist also.

**Comment by sebky94** [comment]
Hello, 

@jaco-iBez could you please tell me how you can see the packets in the influxDB? 

Thank you.

**Comment by lmangani** [comment]
@sebky94 heplify-server exposes a prometheus metric endpoint InfluxDB 2.0 can scrape, or you can scrape it with Telegraf - both cases are available in our examples. How are you installing and what versions are you using?

**Comment by sebky94** [comment]
@lmangani I have HOMER 7, i uploaded the install in this link : **https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh** 
then changed the rights and executed it using **./homer_installer.sh**
and now i have this dashboard : 

![image](https://user-images.githubusercontent.com/54589211/70057204-0be90e00-15dd-11ea-9d8f-dee0d9a29696.png)

**Comment by sebky94** [comment]
@lmangani i'm not familiar with managing Data Bases so i'm not used to scraping, could you please assit me ?

**Comment by Justessej** [comment]
@sebky94 I have the same problem i have the dashboard but what is the next step?

**Comment by lmangani** [comment]
As discussed in other threads: We are decommissioning the 7.0 release shortly and replacing it with 7.7 so please update your setups in order to get assistance! If you get stuck installing 7.7 open a dedicated issue - you will not be disappointed - thanks!
