### ISSUE TITLE
hom7-timescaledb-all grafana uses prometheus datasource

### ISSUE THREAD

**Issue by barzog** [sipcapture/homer7-docker#130]
Is anyone using that? Because all grafana dashboards in hom7-timescaledb-all/grafana/provisioning/dashboards/ (except TImescale-1573382511698.json) using prometheus datasource which is not defined in hom7-timescaledb-all/grafana/provisioning/datasources/datasource.yml.
Furthemore in that datasource loki datasource is defined, which is not defined in docker-compose.
Only existing timescale dashboard shows SIP Messages (which is OK) and constanly increasing line with heplify packes (I assume there should be gauge).

Someone can share working timescale dashboards?

**Comment by lmangani** [comment]
Hello @barzog 
No - and if there are any users, they are hiding well (which is not all that uncommon) We're happy to take any input to revive this attemtpt which only needs users to evolve. Our general direction is a bit different and will be presented in the coming months.

**Comment by barzog** [comment]
Sad to hear, but I got the point. We revert to standard prometheus installation then.

**Comment by lmangani** [comment]
@barzog I wish I had better news, this had lots of potential but yeah. On the other hand, we made [qryn](https://qryn.dev) to replace this dependency at the core for logs, metrics and telemetry and this will be the building block of HOMER next.
