### ISSUE TITLE
Add  Auth Token ENV variables to Docker Container

### ISSUE THREAD

**Issue by palmtown** [sipcapture/homer7-docker#134]
Hello,

The reason for this issue is to request that docker container environment variables be added for **enable_token_access** and **auth_token_header** as added in commit https://github.com/sipcapture/homer-app/commit/0cd50fbaf5c14a4e1090cfcce56d28b4c5c8ebf5

Note that these variables are in the webapp_config.json file.

Thank you for your time.

**Comment by adubovikov** [comment]
@palmtown please make a PR

**Comment by palmtown** [comment]
Hello @adubovikov 

Absolutely, will do!

**Comment by palmtown** [comment]
Note that I have created the pull request at https://github.com/sipcapture/homer7-docker/pull/135.  Also, note that the environment variables will need to be added to webapp_config.json doing docker provisioning.
