### ISSUE TITLE
Homer web GUI not showing query results

### ISSUE THREAD

**Issue by solarmon** [sipcapture/homer7-docker#136]
Hi,

I have a homer7-docker/heplify-server/hom7-prom-all setup that is receiving HEP packets from opensips. I have two such Homer servers and our opensips servers is configured to send to both at the same time.

The setup has been working, but recently, one of them has stopped displaying query results in the web GUI. The Grafana part of the setup seems to still be working - as the graphs are displaying the stats for ingested traffic.

The Homer version is 7.10.21, and running on a CentOS 7.9 system. `docker ps` suggests that all the dockers are running OK.

The last thing that was done was to update the docker-compose.yml file - for the HEPLIFYSERVER_PROMTARGETIP and HEPLIFYSERVER_PROMTARGETNAME values .These variables was updated on both Homer servers, which are using the same variables and values generated with a script - so I'm confident that the details are the same.

Both Homer systems were then updated with `docker-compose  pull` and restarted with `docker-compose update -d`

I was sure that both were working after the updates - i.e. returning query results. However, a day or two later, one of them stopped displaying the query results.

I've checked disk space, and that seems to be OK on the Homer server that has this issue.

Since Grafana graphs seem to working, what else can I check on the Homer web GUI side to find out why the the query results are not showing up.

Thank you.

**Comment by solarmon** [comment]
Output from `db` docker with command `psql -h 'localhost' -U 'root' -c '\l'`

![image](https://user-images.githubusercontent.com/46369787/196695573-46284618-6e9d-409b-85b4-afb5f43ea101.png)

**Comment by adubovikov** [comment]
please also provide the output of these commands:

```
SELECT * FROM pg_stat_activity WHERE state = 'active';

SELECT * FROM pg_stat_activity;

```

**Comment by solarmon** [comment]
![image](https://user-images.githubusercontent.com/46369787/196697563-8650de3d-31a9-4563-9cfb-8ff1a967f716.png)

**Comment by adubovikov** [comment]
the issue has been resolved after restart DB container
