### ISSUE TITLE
Typo in docker-compose.yml environment variables

### ISSUE THREAD

**Issue by LtdJorge** [sipcapture/homer7-docker#139]
Hi, there's a typo in the main compose file:
"HEPLIFYSERVER_DBSHEMA=homer7" (shema/schema)

Is this a bug in the compose file, or a bug in the HEPlify server?

**Comment by lmangani** [comment]
Well. Technically its a typo, but that's the actual setting in the [code](https://github.com/sipcapture/heplify-server/blob/842d096811ca91f58a6dd6137f4c61f0ef983273/config/webconfig.go#L44) so the compose is actually correct.

**Comment by LtdJorge** [comment]
Thanks for clarifying
