### ISSUE TITLE
Fresh homer7-docker/heplify-server/hom7-prom-all/ - Grafana dashboards not working

### ISSUE THREAD

**Issue by idanam-del** [sipcapture/homer7-docker#142]
Hey, out of fresh docker-compose of hom7-prom-all, all of the default dashboards in Grafana except "host overview" dashboard are not showing any information,

I've validated the homer app with hepgen and i could see the captures there but not in the graphs on grafana.

Am i missing something? i understand this supposed to work out of the box

**Comment by naqashsaeed** [comment]
hi @idanam-del, I have tested your scenario with hepgen traffic and i can see data in dashboards other then "host overview" as well.

Steps:
1) Clone latest Homer-docker from https://github.com/sipcapture/homer7-docker.
2)  Navigate to `/homer7-docker/heplify-server/hom7-prom-all` and run` docker-compose up -d`
3) Now all containers are running fine, access you Grafana and homer UI.
4) Send hepgen traffic using command mention [here](https://github.com/sipcapture/homer/wiki/HEPGEN-Test).
5) First go to Homer UI and you will see your traffic there.
6) Now, go to Grafana UI and check dashboard you will see related data in other dashboards as well.

![image](https://github.com/user-attachments/assets/2bfa0654-9959-4028-9e20-82d7ed644314)
![image](https://github.com/user-attachments/assets/884b4582-0623-445f-8d5b-170881dec90f)
