### ISSUE TITLE
Kamailio Configuration

### ISSUE THREAD

**Issue by medOualla** [sipcapture/homer7-docker#143]
Hello,

Is there any configuration script for kamailio, to connect with the database and show the traffic? I don't have a great knowledge on the kamailio to do it, kamailio will be the the SIP proxy between SIPp callee and SIPp caller...

Thanks

**Comment by lmangani** [comment]
Hi @medOualla 

- if you do not have experience configuring Kamailio, you might want to try a passive HEP agent such as [heplify](gttosL..github.com/sipcapture/heplify)
- if you want to go pro, use the kamailio siptrace module following its docs or starting from [here](https://github.com/sipcapture/homer/wiki/Examples:-Kamailio#kamailio-5x-trace-node)

hope this helps
