### ISSUE TITLE
- environment variables

### ISSUE THREAD

**Issue by idanam-del** [sipcapture/homer7-docker#144]
hey, what are the environment variables for docker-compose.yml?

### **- In**

 https://github.com/sipcapture/homer7-docker/tree/master/heplify-server/hom7-prom-all

thank you

**Comment by naqashsaeed** [comment]
@idanam-del you can find environment variables for docker-compose.yml file [here](https://github.com/sipcapture/homer7-docker/blob/master/heplify-server/hom7-prom-all/docker-compose.yml):
