### ISSUE TITLE
The problem with LDAP group in homer-webapp docker container

### ISSUE THREAD

**Issue by perrfect** [sipcapture/homer7-docker#145]
Hello.
I have some problems with **LDAP_USERGROUP** in the **homer-webapp** docker container in a **/usr/local/homer/etc/webapp_config.json** config.
When the container has restarted **usergroup** are changed from `"usergroup": "sec_homer_users"` to `"usergroup": "sec_roots"`.
Only removing the container helps
This group I forward to the config via docker-compose, as:
`"LDAP_USERGROUP=sec_homer_users"`

**Comment by kYroL01** [comment]
Duplicate issue - the same is already resolved here https://github.com/sipcapture/homer/issues/592
