### ISSUE TITLE
h248 and Diameter support

### ISSUE THREAD

**Issue by leonwangcn** [sipcapture/homer7-docker#15]
Hello,

Do you have plan to support H.248 protocol and Diameter protocols?
Or is there any fast way to support a new protocol?
Thanks!

Regards,
Leon

**Comment by lmangani** [comment]
Hi @leonwangcn 

Generally speaking, H7 can handle anything an HEP Agent can send it by defining a schema, this is how we can also make CDRs or RTC Events indexed and/or cross-correlated. I believe this is still being fully documented and was only illustrated in our recent presentations, so keep an eye our for our upcoming posts.

CaptAgent already has Diameter support, and many more protocols are coming if you'd like to test and/or contribute new dissectors and objects please help yourself or open a specific issue

Thanks!

**Comment by leonwangcn** [comment]
Thanks!
We will try to add a new protocol support (MEGACO).
