### ISSUE TITLE
Can homer use mysql instead postgres as database backend?

### ISSUE THREAD

**Issue by eriklee1895** [sipcapture/homer7-docker#150]
My product environment has alred depolyed mysql cluster, so I'd like to know whether homer can use mysql as database storage?
Thanks!

**Comment by ChaerilM** [comment]
according to #115 and [homer10](https://github.com/sipcapture/homer/issues/419) you cant, heplify-server probably can write to mysql. but homer is fully written for pgsql

**Comment by kYroL01** [comment]
Correct, Homer cannot support mysql, as it was designed not to use it.
 As @ChaerilM said you might try to see if heplify-server can, but afaik this is something you can do at your risk.
