### ISSUE TITLE
hom7-prom-all: Old grafana 8.3.5 is being used because grafana/grafana:master image in docker-compose.yml

### ISSUE THREAD

**Issue by maltris** [sipcapture/homer7-docker#151]
I've been made aware that my old grafana 8.3.5 installation that came out of the box with hom7-prom-all is outdated and contains some security vulnerabilities. Upon digging in a little, I found that the grafana/grafana:master image havent been updated since 2 years (https://hub.docker.com/r/grafana/grafana/tags?page=1&name=master).

Question: Is this on purpose due to an incompatibility with another homer component or because that docker image tag hasnt been updated for so long?

**Comment by lmangani** [comment]
@maltris you're a bit out of the loop, here's the latest: https://github.com/sipcapture/homer-docker/tree/main/all-in-one
