### ISSUE TITLE
Doesn't start up

### ISSUE THREAD

**Issue by Dazez** [sipcapture/homer7-docker#18]
Hello,
I've composed hom7-hep-influx package, but I can't get to Homer page, even though it logs "Server started".

It also logs this: _E! Error in plugin [inputs.prometheus]: error making HTTP request to http://heplify-server:9096/metrics: Get http://heplify-server:9096/metrics: dial tcp 172.18.0.6:9096: connect: connection refused_

I don't really know how to solve this, it is quite different from H5, which worked to me, except of long msg database problem, that's why I am trying H7.

**Comment by lmangani** [comment]
Hi @Dazez 
There are a lot of variables at play here. Try run the compose in front-end and watch out for any errors from the containers we can look at together. Thanks!

**Comment by Dazez** [comment]
what about this?
  _0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to chronograf port 80: Connection refused_

**Comment by lmangani** [comment]
Those are just snoball effects. Pretty much nothing is going to work since the core services are not up or reachable. First time with Docker?

**Comment by lmangani** [comment]
Please attach the output of `docker ps` (unless you have other containers running it should tell the story)

**Comment by Dazez** [comment]
First time with H5, but still only a few days.
```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                    PORTS                                                                                            NAMES
3c1b24ebe9ed        telegraf:1.8-alpine           "/entrypoint.sh tele…"   2 hours ago         Up 17 seconds             0.0.0.0:8092->8092/udp, 0.0.0.0:8125->8125/udp, 8094/tcp                                         hom7hepinflux_telegraf_1
f1f9dd10bc0a        sipcapture/homer-app:master   "/docker-entrypoint.…"   2 hours ago         Up 20 seconds             80/tcp, 443/tcp, 8001/tcp                                                                        homer-webapp
c61014a7d3b6        sipcapture/hepop:master       "/docker-entrypoint.…"   2 hours ago         Up 19 seconds             8080/tcp, 9090/tcp, 0.0.0.0:9060->9060/tcp, 0.0.0.0:9060->9060/udp                               heplify-server
537acd3c645d        chronograf:1.6                "/entrypoint.sh chro…"   2 hours ago         Up 21 seconds             8888/tcp                                                                                         hom7hepinflux_chronograf_1
2712da37b976        kapacitor:1.5-alpine          "/entrypoint.sh kapa…"   2 hours ago         Up 24 seconds             9092/tcp                                                                                         hom7hepinflux_kapacitor_1
4bc87eaf5b03        postgres:11-alpine            "docker-entrypoint.s…"   2 hours ago         Up 25 seconds (healthy)   5432/tcp                                                                                         hom7hepinflux_db_1
0f7cd9360677        influxdb:1.6-alpine           "/entrypoint.sh infl…"   2 hours ago         Up 27 seconds             8086/tcp                                                                                         hom7hepinflux_influxdb_1
b32ce45f001e        stefanprodan/caddy            "/sbin/tini -- caddy…"   2 hours ago         Up 25 seconds             0.0.0.0:3000->3000/tcp, 0.0.0.0:9080->9080/tcp, 0.0.0.0:9090->9090/tcp, 0.0.0.0:9093->9093/tcp   caddy
```

**Comment by lmangani** [comment]
Can you reach port `80` or `9080` at all on the `homer-app` container?

**Comment by Dazez** [comment]
That is a surprise, the port 9080 actually works, I didn't expected another port that those 80/443/8001, and unfortunately it isn't listed anywhere where I was looking into. I'll test it.
Thanks a lot!

**Comment by Dazez** [comment]
port 9060 is then for HEP messages, right?
When Kamailio sends there its HEP messages, this log pops up several times:
heplify-server    | [03:36:48 PM] ✖️ TypeError: Cannot read property 'payloadType' of undefined
heplify-server    | [03:36:48 PM] TypeError: Cannot read property 'correlation_id' of undefined

**Comment by lmangani** [comment]
The ports are listed on the container details. Make sure you are sending `HEP3`

**Comment by Dazez** [comment]
Version was the issue, I thought that Kamailio supports only HEP1 and 2, they haven't another option in module documentation.
Now everything I need works. Thanks for your help.

**Comment by lmangani** [comment]
Glad we could help!
