### ISSUE TITLE
Registration searching

### ISSUE THREAD

**Issue by Dazez** [sipcapture/homer7-docker#19]
Hi, any call searching is working just fine, but when I try to search something in the registration profile, nothing shows up, but logically that data should be there, when calls are ok. Maybe there is problem with registration profile itself, but I don't know how to debug something like this. When I try to search, this log pops up in CLI up:
```
2019-03-21 19:32:49.194 UTC [785] ERROR:  relation "hep_proto_1_registration" does not exist at character 119
db_1              | 2019-03-21 19:32:49.194 UTC [785] STATEMENT:  select "id", "sid", "protocol_header", "data_header", ROUND(EXTRACT(epoch FROM create_date)*1000) as create_date from "hep_proto_1_registration" where "create_date" between $1 and $2 limit $3
homer-webapp      | Debug: handler, error 
homer-webapp      |     {"msec":2.069543999619782,"error":"select \"id\", \"sid\", \"protocol_header\", \"data_header\", ROUND(EXTRACT(epoch FROM create_date)*1000) as create_date from \"hep_proto_1_registration\" where \"create_date\" between $1 and $2 limit $3 - relation \"hep_proto_1_registration\" does not exist","data":{"name":"error","length":124,"severity":"ERROR","code":"42P01","position":"119","file":"parse_relation.c","line":"1180","routine":"parserOpenTable","isBoom":true,"isServer":true,"output":{"statusCode":503,"payload":{"statusCode":503,"error":"Service Unavailable","message":"select \"id\", \"sid\", \"protocol_header\", \"data_header\", ROUND(EXTRACT(epoch FROM create_date)*1000) as create_date from \"hep_proto_1_registration\" where \"create_date\" between $1 and $2 limit $3 - relation \"hep_proto_1_registration\" does not exist"},"headers":{}}}}
```

HEP messages containing REGISTER dialog messages are coming to Homer without error.

**Comment by negbie** [comment]
Hi @Dazez 
it must be hep_proto_1_register 
NOT hep_proto_1_registration

**Comment by negbie** [comment]
Currently these should work:

hep_proto_1_call
hep_proto_1_register
hep_proto_1_default
hep_proto_5_default
hep_proto_35_default
hep_proto_53_default
hep_proto_54_default
hep_proto_100_default

**Comment by negbie** [comment]
Since it's somehow related you can ping the guys here too. https://github.com/sipcapture/homer-app/issues/50

**Comment by negbie** [comment]
Ok I changed this in heplify-server so it will write register into hep_proto_1_registration
Please pull the heplify-server image again

**Comment by Dazez** [comment]
I used command `docker-compose pull heplify-server`.
Then when I did the same as before, searched using the registration profile, again nothing showed up, but also the log didn't. 
But I've come to a solution...just renaming the profile from "registration" to "register" solves it.

**Comment by negbie** [comment]
Hi,
mby the auto build was not ready? Do you use the master tag? Here you can find all tags
https://hub.docker.com/r/sipcapture/heplify-server/tags

Keep in mind that from now on it is hep_proto_1_registration

**Comment by Dazez** [comment]
It works now.
Thanks for your time.
