### ISSUE TITLE
[hom7-hep-elastic] "stats data has been not found" just after running docker-compose up

### ISSUE THREAD

**Issue by gpavinteractiv** [sipcapture/homer7-docker#23]
On Centos 7.6
 
````
cd /opt/
git clone https://github.com/sipcapture/homer7-docker.git
cd /opt/homer7-docker/heplify-server/hom7-hep-elastic/
docker-compose up
````

I see the following errors : 

````
homer-webapp      | Error....
homer-webapp      | Debug: handler, error 
homer-webapp      |     {"msec":4.11526899994351,"error":"stats data has been not found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"stats data has been not found"},"headers":{}}}}
homer-webapp      | Error....
homer-webapp      | Debug: handler, error 
homer-webapp      |     {"msec":4.080958999926224,"error":"stats data has been not found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"stats data has been not found"},"headers":{}}}}
....
````
I activated sip capture on my test Freeswitch and configured it to point to homersrv:9060
I can not find any data in either Homer or Kibana yet ; Am I doing anything wrong?

**Comment by lmangani** [comment]
Hi @gpavinteractiv 
When using this bundle, there will be no statistics visible in the HOMER UI, only Kibana.
Please check and confirm if you see any traffic towards your Elasticsearch API from HEPlify-Server (packets) and/or Telegraf (metrics) to start with.

**Comment by lmangani** [comment]
NOTE: If you want an Elastic-only deployment from a data perspective check this too: https://github.com/sipcapture/homer7-docker/tree/master/hepop/hom7-elastic-only

**Comment by gpavinteractiv** [comment]
I confirm packets are coming to 9060 ; 

I was expecting being able to use HOMER interface (to browse calls, see messages and check the flow) with this bundle as it is available on 9080. I must be confused by something.

I am trying with heplify-server/hom7-hep-influx now and that seem to be working more as expected.

**Comment by lmangani** [comment]
@gpavinteractiv that's definitely the case, but each bundle goes in a very different direction and indeed that might be confusing until we consolidate the public preferences. You might want to make your own recipe to sum features up until then, feel free to ask help here if needed.
