### ISSUE TITLE
Error in H7 + InfluxDB docker installation 

### ISSUE THREAD

**Issue by tandelDipak** [sipcapture/homer7-docker#32]
Hi 
I am using Debian 9. I downloaded docker file for H7 + InfluxDB docker installation from [here](https://github.com/sipcapture/homer7-docker/blob/master/heplify-server/hom7-hep-influx/docker-compose.yml). But facing issue while running docker-compose up command.

The output of the docker-compose up command is attached below.

![Screenshot from 2019-06-28 15-05-27](https://user-images.githubusercontent.com/15157792/60333637-2b896400-99b7-11e9-91e1-d2506a95a280.png)

**Comment by lmangani** [comment]
Hi @tandelDipak 

The error seems pretty clear, it can't find the expected file it wants to mount
```
- ./conf/telegraf.conf:/etc/telegraf/telegraf.conf
```

make sure you are in the correct directory for the above path to work when launching `docker-compose up`

**Comment by tandelDipak** [comment]
Hi @lmangani 

What is the correct directory for the above path to work?

**Comment by lmangani** [comment]
You should be in the folder where the `docker-compose` file is located, all mount paths are local. If this is already the case, do make sure the file it attempts to mount IS actually there. Hope this helps!

**Comment by tandelDipak** [comment]
Can you please elaborate more on "**make sure the file it attempts to mount IS actually there**". I don't know how to achieve this.
