### ISSUE TITLE
Homer7 configuration for docker-compose

### ISSUE THREAD

**Issue by tandelDipak** [sipcapture/homer7-docker#38]
Hi team

I have one CentOS VM with two NIC. On one NIC SIP traffic is coming and the second one is being used for internet and management. Only the second NIC has an IP address. docker-compose up is running properly for [HEPlify + InfluxDB + LoudML.](https://github.com/sipcapture/homer7-docker/tree/master/heplify-server/hom7-hep-influx)

When I ran Wireshark trace on NIC one, I am getting SIP packets. But I don't have anything in database and homer app. Can anyone help here?
Here NIC one is receiving mirrored traffic from the switch. 

I can see that Heplify-server is listening on port 9060. What configuration I have to do to send NIC traffic (Raw packet) to Heplify-server?

**Comment by tandelDipak** [comment]
@lmangani  can you help here?

**Comment by lmangani** [comment]
Hi @tandelDipak I already explained the very same thing via email. You  need to install HEPlify where you receive packets - it will capture and send HEP to HEPlify-Server itself.
