### ISSUE TITLE
hom7-hep-elastic - No dashboard graphs

### ISSUE THREAD

**Issue by lukeescude** [sipcapture/homer7-docker#41]
I've been playing with these settings all day, and can't find any documentation or rhyme or reason as to why I can't add the usual SIPCapture statistics to Homer 7. (the same stats available on the dashboard of Homer 5).

Anyone have any advice for getting some stats in Homer 7?

See attached.

Thanks all!
<img width="785" alt="Screen Shot 2019-09-17 at 9 04 54 PM" src="https://user-images.githubusercontent.com/11986333/65101944-3c7ebb80-d98f-11e9-93ba-92589f1bdedc.png">

**Comment by lukeescude** [comment]
Here, I'll attach an example of our current Homer 5 deployment I am trying to create in Homer 7.

An all SIP packets graph, an INVITE only graph, and a REGISTER only graph.
<img width="1115" alt="Screen Shot 2019-09-17 at 9 12 43 PM" src="https://user-images.githubusercontent.com/11986333/65102252-14438c80-d990-11e9-8b0c-eb9bd8f807c7.png">

**Comment by mcebey1891** [comment]
I have the same problem. And if I try to put by hand the configuration it doesn't work properly.

**Comment by lmangani** [comment]
FYI @lukeescude your data is in Elasticsearch. HOMER does not read from Elastic, it just writes to it. Replicate those dashboards in Kibana to use the real power of your backend of choice ;)
