### ISSUE TITLE
Loki continually restarting

### ISSUE THREAD

**Issue by mcebey1891** [sipcapture/homer7-docker#43]
Hi,
I'm trying Homer7 with HEPlify + Prometheus + Loki but the Loki container is continually restarting and I can't find any explanation of that.

Any suggestion?

Thanks

**Comment by lmangani** [comment]
What are the logs saying? This could be related to an incompatible (or outdated) configuration file

**Comment by mcebey1891** [comment]
Hi,
If I run the comand:
docker-compose logs loki

The system returns a lot of:

loki  | level=error ts=2019-09-30T20:22:16.612518561Z caller=main.go:48 msg="error loading config" filename=/etc/loki/loki-local-config.yaml err="yaml: unmarshal errors:\n  line 10: field store not found in type ring.Config"

**Comment by mcebey1891** [comment]
Hi,

Hello,
I think I solved the problem.
In the configuration file, I change the entry:
**ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      store: inmemory
      replication_factor: 1
  chunk_idle_period: 15m**

Adding the line 

> kvstore:

**ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
       store: inmemory
      replication_factor: 1
  chunk_idle_period: 15m**

Then, I stop the Loki container, remove them and then execute:
docker-compose up -d

And works.

Thanks
