### ISSUE TITLE
No MOS values or graphs

### ISSUE THREAD

**Issue by fourti** [sipcapture/homer7-docker#45]
Hi,

we have a setup with rtpengine in the middle between two SIP-Endpoints which both sends RTCP informations.
We have the RTCP packets in homer7 (hom7-hep-influx), but homer7 doesn't show any MOS values or graphs.
![grafik](https://user-images.githubusercontent.com/20302828/67266039-85a2bd80-f4af-11e9-9c6f-ddb0fb45a400.png)

Is there anything missing on our side?

**Comment by hvspa** [comment]
did you get this resolved?

**Comment by fourti** [comment]
Nope. Maybe homer 7.7 has it now, but I didn't check that yet.
I know that the commercial product from qxip can do it, or other commercial software.

**Comment by adubovikov** [comment]
Homer 7.7 has MOS base on RTCP information
https://github.com/sipcapture/homer/wiki/Quick-Install

**Comment by adubovikov** [comment]
We have fixed that issue in the UI 7.7.028. Please update the image

**Comment by hvspa** [comment]
> We have fixed that issue in the UI 7.7.028. Please update the image

for me under 028, QOS XRTP has no data :(

**Comment by adubovikov** [comment]
what is it QOS XRTP ?

**Comment by lmangani** [comment]
The definition sounds ancient. Please attach a screenshot.

**Comment by hvspa** [comment]
> 
> 
> The definition sounds ancient. Please attach a screenshot.

here you go
![qos xrtp](https://user-images.githubusercontent.com/27876987/75095763-ee12c000-55b1-11ea-8e64-54e5a8747696.PNG)

**Comment by hvspa** [comment]
here is qos rtcp
![qos rtcp](https://user-images.githubusercontent.com/27876987/75095780-139fc980-55b2-11ea-80d4-2b95e2b312e7.PNG)

**Comment by hvspa** [comment]
> 
> 
> what is it QOS XRTP ?
dashboard in grafana :)

**Comment by adubovikov** [comment]
> > what is it QOS XRTP ?
> > dashboard in grafana :)

great,  it says so much. Do you have any X-RTP-Stats or PUBLISH Vqrtcp ?

**Comment by hvspa** [comment]
> 
> 
> > > what is it QOS XRTP ?
> > > dashboard in grafana :)
> 
> great, it says so much. Do you have any X-RTP-Stats or PUBLISH Vqrtcp ?

where do i check that? 

i've just enabled packets sending by  ./heplify -hs dst:9060 -hn ast_int

**Comment by adubovikov** [comment]
it has nothing todo with the subj of this topic. Please check this:
https://tools.ietf.org/html/rfc6035
https://www.voip-info.org/rtcp-xr/

**Comment by hvspa** [comment]
> 
> 
> it has nothing todo with the subj of this topic. Please check this:
> https://tools.ietf.org/html/rfc6035
> https://www.voip-info.org/rtcp-xr/

ok, thanks very much.
