### ISSUE TITLE
How to update homer?

### ISSUE THREAD

**Issue by Justessej** [sipcapture/homer7-docker#52]
Is there a command or a instruction of commands?

**Comment by lmangani** [comment]
It depends on your starting point - what's your current version or how did you install? 
Mind, Homer is not a single application but rather a bundle of components.

**Comment by lmangani** [comment]
I almost did not notice we're on the Docker repository; Just switch to the `7.7` branch containers and you should have to do very little.

**Comment by Justessej** [comment]
Do u have a video how to install docker?

**Comment by Justessej** [comment]
@lmangani

**Comment by lmangani** [comment]
@Justessej the internet is full of excellent guides on how to install `docker` and `docker-compose` on your Operating System. Once you did, you can just follow the instructions.
