### ISSUE TITLE
SIP Metric (ASR & NER) by traffic origin 

### ISSUE THREAD

**Issue by benhamoua** [sipcapture/homer7-docker#55]
Hi,

I m using hom7-prom-all 7.7  and faced a problem with KPI, i have add direction tag to the metric in order to differentiate  target traffic direction Incoming or Outgoing:

clamp_max((sum(increase(heplify_method_response{target_name=~"$tn", direction="src", method="INVITE", response="200"}[30m])) * 100) / 
(sum(increase(heplify_method_response{target_name=~"$tn", direction="src", method="INVITE", response="INVITE"}[30m]))

**Comment by negbie** [comment]
1. Please formulate a real question and make it clear what you want.
2. This is the wrong repo and you should create this issue under heplify-server.
3. Maybe you just need to set the origin under PromTargetIP and give it a PromTargetName.

**Comment by benhamoua** [comment]
Thank's.

the purpose is to have KPI for Incoming traffic and outgoing separated, i have already add PromtagretIp & Promtargetname but the metric calculate all trafic IN & OUT at the same time.

in my case i have diffrenete trunk and each one is used for both direction.

so is it possible to add metric for incoming traffic and second metric for outgoing traffic for the same PromtargetIP ? thank's for help
