### ISSUE TITLE
hom7-influx-tick - Cannot open call log

### ISSUE THREAD

**Issue by im-voiceon** [sipcapture/homer7-docker#57]
Hello

I am running homer7-docker/heplify-server/hom7-influx-tick branch 7.7.
Browser: Chrome 79.0.3945.117
Every time when I click to Session ID (Call Id) I am getting javascript error:

ERROR TypeError: Cannot read property 'protocol_id' of null
at SearchGridCallComponent.push../src/app/components/search-grid-call/search-grid-call.component.ts.SearchGridCallComponent.queryBuilderQOS (main.b0c0ae891134c32fe5c6.js:321570)
at SearchGridCallComponent.push../src/app/components/search-grid-call/search-grid-call.component.ts.SearchGridCallComponent.openTransactionDialog (main.b0c0ae891134c32fe5c6.js:321886)
at SearchGridCallComponent.push../src/app/components/search-grid-call/search-grid-call.component.ts.SearchGridCallComponent.openTransactionForSelectedRows (main.b0c0ae891134c32fe5c6.js:321828)
at ColumnCallidRenderer.push../src/app/components/search-grid-call/renderer/column-callid-renderer.component.ts.ColumnCallidRenderer.openTransactionPopup (main.b0c0ae891134c32fe5c6.js:321183)
at ColumnCallidRenderer_Template_a_click_0_listener (template.html:1)
at executeListenerWithErrorHandling (main.b0c0ae891134c32fe5c6.js:86868)
at wrapListenerIn_markDirtyAndPreventDefault (main.b0c0ae891134c32fe5c6.js:86896)
at HTMLAnchorElement. (main.b0c0ae891134c32fe5c6.js:160133)
at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (polyfills.db252f9f61df52652520.js:3271)
at Object.onInvokeTask (main.b0c0ae891134c32fe5c6.js:97771)

The same issue for homer7-docker/heplify-server/hom7-prom-all

**Comment by Woutch** [comment]
Dear All,

I have the same problem with homer7-docker/heplify-server/hom7-prom-all. 

Clean install with the following changes to the docker compose file: (To get all data in Grafana, see issue #50)
      - "HEPLIFYSERVER_PROMTARGETIP="
      - "HEPLIFYSERVER_PROMTARGETNAME="

Thanks
Wouter

**Comment by im-voiceon** [comment]
Dear Wouter,
I assume you're talking about empty logs in Grafana. In my case, I cannot open the dialog box in the main UI when I click on SessionId because of a JavaScript error.

Ildar

**Comment by adubovikov** [comment]
please wait. We will update the images ASAP

**Comment by im-voiceon** [comment]
That's very interesting. Now the dialog box opens, but the call flow is not displayed correctly. An illustration with the wrong and correct flow attached 
![CallFlow](https://user-images.githubusercontent.com/50916518/72505739-9a45e600-3851-11ea-99a8-258eae8b597e.png)
.

**Comment by im-voiceon** [comment]
We have such issue on every call.  
Call export example:

proto:UDP 2020-01-16T07:48:33.332581Z  37.49.230.28:6284 ---> 116.***.**.**2:5060

INVITE sip:994441519460055@116.***.**.**2:5060 SIP/2.0
Via: SIP/2.0/UDP 37.49.230.28:6284;branch=z9hG4bK2f6f7ce6-117e-3846-pbp70zvtnipvih0k;rport
Max-Forwards: 70
Contact: <sip:8892564023@37.49.230.28:6284>
To: <sip:994441519460055@116.***.**.**2:5060>
From: <sip:8892564023@37.49.230.28:6284>;tag=g678i9u7543w8nob
Call-ID: oedUoMr7zm2by1V9nbOVs4MLvB3rsntiHaveMFq5
CSeq: 1 INVITE
User-Agent: Cisco-SIPGateway/IOS-12.x
Content-Type: application/sdp
Content-Length: 0


proto:UDP 2020-01-16T07:48:33.353267Z  116.***.**.**2:5060 ---> 37.49.230.28:6284

SIP/2.0 405 Not authorized
Via: SIP/2.0/UDP 37.49.230.28:6284;branch=z9hG4bK2f6f7ce6-117e-3846-pbp70zvtnipvih0k;rport=6284;received=37.49.230.28
To: <sip:994441519460055@116.***.**.**2:5060>;tag=6fcd9ef7b99d49be2a1903a0afc34d28.dede5c63
From: <sip:8892564023@37.49.230.28:6284>;tag=g678i9u7543w8nob
Call-ID: oedUoMr7zm2by1V9nbOVs4MLvB3rsntiHaveMFq5
CSeq: 1 INVITE
Server: kamailio (5.3.0 (x86_64/linux))
Content-Length: 0


proto:UDP 2020-01-16T07:48:33.380708Z  37.49.230.28:6284 ---> 116.***.**.**2:5060

ACK sip:994441519460055@116.***.**.**2 SIP/2.0
Via: SIP/2.0/UDP 37.49.230.28:6284;branch=z9hG4bK2f6f7ce6-117e-3846-pbp70zvtnipvih0k;rport=6284;received=37.49.230.28
To: <sip:994441519460055@116.***.**.**2:5060>;tag=6fcd9ef7b99d49be2a1903a0afc34d28.dede5c63
From: <sip:8892564023@37.49.230.28:6284>;tag=g678i9u7543w8nob
Call-ID: oedUoMr7zm2by1V9nbOVs4MLvB3rsntiHaveMFq5
CSeq: 1 ACK
Max-Forwards: 70
User-Agent: Cisco-SIPGateway/IOS-12.x
Content-Type: application/sdp
Content-Length: 296

v=0
o=io 146093579 148097614 IN IP4 37.49.230.28
s=io
c=IN IP4 37.49.230.28
t=0 0
m=audio 20001 RTP/AVP 100 6 0 8 3 18 5 97 98 9 99 13 102 121 105 101
a=alt:1 1 : C27EB8F2 C9259ACC 37.49.230.28 6284
a=fmtp:101 0-15
a=rtpmap:100 speex/16000
a=rtpmap:101 telephone-event/8000
a=sendrecv

**Comment by Woutch** [comment]
Very strange,
It is still not working on my side. I removed all containers + volumes and started from scratch. (hom7-prom-all).

Still seeing the error: "ERROR TypeError: Cannot read property 'protocol_id' of null"
But I do see some extra prints to console with some data in, so I guess the image has been been updated.

Tell me if you need some more information.

Thanks,
Wouter

**Comment by Woutch** [comment]
@adubovikov Can we have an update please on this issue? 

I have refreshed the homer images several times when I see an update on dockerhub but still the same problem.

We want to monitor our newer PBX servers where we are using pjsip, this is not working with our older Homer 5 installation.

Many thanks!!
Wouter

**Comment by adubovikov** [comment]
@Woutch sorry, do you see any records in the database ? Can you check your F12 Web console and see if the search/call/data API returns any data ? Can you paste it here ?

**Comment by Woutch** [comment]
Hi, 

Gathering from your answer it should work, so:

I just updated again using docker-compose pull / docker-compose restart. But was still not working. Then deleted all volumes, but still not working.
Then deleted the "postgres-data" folder and rebuild all containers.

**Now it is working!!!**

- Is there a good migration path to update these containers?
- As a short side question, is there a possibility to see the MOS score? This was show in Homer5.

Many thanks for your help!!!

Best regards,
Wouter

**Comment by lmangani** [comment]
Hi @Woutch glad you figured this already. As of your questions:

* Yes, the upgrades should "migrate" the database schema and tables going forward
* There are multiple ways now. I guess you're referring the to "fake" MOS calculated from RTCP - this is currently hidden for maintenance, and shall reappear sometime during this or next week.

Thanks for testing & submitting an issue! Feel free to comment further if needed
