### ISSUE TITLE
loki home page not found

### ISSUE THREAD

**Issue by hvspa** [sipcapture/homer7-docker#59]
hi,
i am very new in grafana/loki/hep and in github as well(sorry for my formatting), trying to run the containers from docker_compose file, where loki looks like:

  loki:
    image: grafana/loki:master
    container_name: loki
    restart: unless-stopped
    expose:
      - 3100
    ports:
      - "3100:3100"
    labels:
      org.label-schema.group: "monitoring"
however, my loki home page is not found:
[r$]# curl http://localhost:3100             
404 page not found
[r$]# 
i am seeing following logs in container of loki, but not sure what those means:
level=info ts=2020-01-29T03:20:14.383411595Z caller=table_manager.go:364 msg="creating table" table=index_2565
level=info ts=2020-01-29T03:20:14.383438423Z caller=table_manager.go:364 msg="creating table" table=index_2521
level=info ts=2020-01-29T03:20:14.383466714Z caller=table_manager.go:364 msg="creating table" table=index_2572
level=info ts=2020-01-29T03:20:14.383494233Z caller=table_manager.go:364 msg="creating table" table=index_2580
level=info ts=2020-01-29T03:20:14.383520919Z caller=table_manager.go:364 msg="creating table" table=index_2603
level=info ts=2020-01-29T03:20:14.383549634Z caller=table_manager.go:364 msg="creating table" table=index_2569

do you think in docker compose some volumes are missing? 

these are the files in the root directory:

[r$]# ls -lrth
total 20K
-rw-r--r--  1 root root 5.0K Jan 29 00:39 docker_compose.yml
drwxr-xr-x  3 root root   25 Jan 29 00:41 grafana
drwxr-xr-x  2 root root    6 Jan 29 00:42 init-user-db.sh
drwxr-xr-x  2 root root   23 Jan 29 00:48 alertmanager
drwxr-xr-x  2 root root   45 Jan 29 00:50 prometheus
drwxr-xr-x  2 root root   22 Jan 29 00:50 caddy
-rw-r--r--  1 root root  238 Jan 29 00:57 to_ring_up.txt
-rw-r--r--  1 root root    1 Jan 29 01:17 bootstrap
drwxr-xr-x  2 root root   83 Jan 29 05:37 loki
drwx------ 19   70 root 4.0K Jan 29 05:37 postgres-data
[r$]#

docker_compose is just copy paste from [here](https://github.com/sipcapture/homer7-docker/blob/7.7/heplify-server/hom7-prom-all/docker-compose.yml)

thanks in advance,

**Comment by hvspa** [comment]
no reply? it is still empyt whatever i do.
i tried this one:
git clone https://github.com/sipcapture/homer7-docker
cd homer7-docker/heplify-server/hom7-prom-all
docker-compose up -d

on a new server and it still returns text "404 page not found"

would appreciate if someone can help on this

**Comment by lmangani** [comment]
You're not supposed to reach the Loki page directly. You should use port 9080 to access Homer.

**Comment by hvspa** [comment]
> 
> 
> You're not supposed to reach the Loki page directly. You should use port 9080 to access Homer.
thnx much for reaching out. 
i know my question is out of topic, but what is the interface for loki? is it some kind of rest api?

**Comment by lmangani** [comment]
that's correct :) 

https://github.com/grafana/loki/blob/master/docs/api.md

**Comment by hvspa** [comment]
ok, thanks much :)
