### ISSUE TITLE
hom7-prom-all problem writing to DB

### ISSUE THREAD

**Issue by marcozink** [sipcapture/homer7-docker#60]
I deleted my old 7 setup and started fresh with 7.7, found that no info was being showed in Prometheus and Homer.

Removing the values from the variables according to #50  did start to fill up Prometheus, thanks for that.

There seems to be a problem writing to the database:

```
db                | 2020-01-29 15:44:30.337 UTC [51] ERROR:  invalid input syntax for type json
db                | 2020-01-29 15:44:30.337 UTC [51] DETAIL:  Token "NOTIFY" is invalid.
db                | 2020-01-29 15:44:30.337 UTC [51] CONTEXT:  JSON data, line 1: ...ion_id":"o: <sip:172.18.0.27:5060>;method="NOTIFY...
db                | 	COPY hep_proto_5_default, line 77, column protocol_header: "{"protocolFamily":2,"protocol":17,"srcIp":"172.18.0.27","dstIp":"172.18.135.98","srcPort":60315,"dst..."
db                | 2020-01-29 15:44:30.337 UTC [51] STATEMENT:  COPY hep_proto_5_default(sid,create_date,protocol_header,data_header,raw) FROM STDIN
```

I pulled the latests version and also deleted everything and cloned from scratch, It seems the database does get created #58, but tables aren't receiving data from the HEP packets being received.

Thanks for the hard work and help.

**Comment by adubovikov** [comment]
Looks like your heplify try to write NOTIFY message to HEP 5 ? (rtcp) IMHO this is not correct way, because for HEP 5 we expect JSON body

**Comment by marcozink** [comment]
Thanks @adubovikov, you are right, so this is a different problem, could it be a bug with the NOTIFY message?

Any idea on how to debug information not showing in homer? I tried connecting to postgre buy was unable to.

**Comment by marcozink** [comment]
Closing since a few hours later information started showing in HomerUI and in DB. Didn't really do anything,

**Comment by lmangani** [comment]
Sounds like a timezone issue? Glad you have data, let us know if you run into any issues and make sure you upgrade the homer-app container often as its updated daily.
