### ISSUE TITLE
hom7-prom-all. No rows to show.

### ISSUE THREAD

**Issue by dima056359** [sipcapture/homer7-docker#61]
Hey guys,

First of all - thanks a lot for your time to develop and maintain such an interesting project!

My issue may be super simple and stupid, but I am wondering why no data was shown to the Web UI when I trying to generate some SIP packets with `hepgen` tool. 

Here is what I did:
- `git clone https://github.com/sipcapture/homer7-docker`
- `cd homer7-docker/heplify-server/hom7-prom-all`
- simply run all the containers needed by firing a `docker-compose up -d` command
- `cd` to `hepgen` folder (outside) and run `node hepgen.js -s 127.0.0.1 -p 9060 -c "./config/b2bcall_rtcp.js"` command
- saw a lot of fake SIP traffic directly to `heplify-server` container on the same machine: `vd: 43, parsed: 27, hepsent: 26, err: 0, heperr: 0`

How it looks like in a Homer Web App:
![image](https://user-images.githubusercontent.com/12616843/73611881-56900200-45ef-11ea-91ad-b190f3e8e9f2.png)

Nothing was changed in config files since `git clone` command (as mentioned above).

**init-user-db.sh:**

```
#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE homer_config;
EOSQL

```

Some logs of `db` container: 
```
PostgreSQL init process complete; ready for start up.

2020-02-02 16:53:09.778 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-02-02 16:53:09.779 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-02-02 16:53:09.802 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-02-02 16:53:09.874 UTC [57] LOG:  database system was shut down at 2020-02-02 16:53:09 UTC
2020-02-02 16:53:09.883 UTC [58] FATAL:  the database system is starting up
2020-02-02 16:53:09.897 UTC [1] LOG:  database system is ready to accept connections
2020-02-02 16:53:12.316 UTC [78] ERROR:  role "postgres" does not exist
2020-02-02 16:53:12.316 UTC [78] STATEMENT:  GRANT postgres to homer_user;
```

Please pay attention at this error: `ERROR:  role "postgres" does not exist`
May it broke the whole system? What is the best way to fix that?

Thanks in advance!

Regards,
Dmitry

**Comment by adubovikov** [comment]
can you please do the update and test one more time ?

**Comment by dima056359** [comment]
Awesome, it works now, thank you so much!
I made tests with Hepgen and Asterisk - everything works smoothly.
Could you tell what caused this issue?

**Comment by adubovikov** [comment]
can be two issues: or wrong config's path, or the image that you had was old :-)
anyway, glad that the issue has been resolved. Enjoy
