### ISSUE TITLE
hom7-prom-all - XRTP Dashboard Empty

### ISSUE THREAD

**Issue by Sp0rN** [sipcapture/homer7-docker#64]
Hi Guys,

Dont really know where else to ask this, as I dont really think its an issue, rather something im overlooking, so apologies in advance.

i have deployed hom7-prom-all, however my XRTP dashboard in Grafana currently shows no data.

![image](https://user-images.githubusercontent.com/31306657/75516182-7a830f80-5a04-11ea-8f59-20c8b4178855.png)

Is this something on hepfliy's end, does it require a certain flag to capture+send XRTP?

These are the flags im using currently:
/usr/bin/heplify -i bond0 -hi 103 -pr 5050-5060 -hs my.hepserver.com:9060 -e -m SIPRTCP

Im receiving all SIP and RTCP data, as the other dashboards populate fine.

Please let me know if this is the incorrect place to post this.

**Comment by negbie** [comment]
Hi @Sp0rN 
XRTP != RTCP

XRTP stats are sent in a BYE request or response to that from the user agent and looks like that:

X-RTP-Stat:
CS=1391;PS=750;ES=751;OS=180000;SP=0/0;SO=0;QS=599;PR=1066;ER=1127;OR=17056
0;CR=0;SR=0;QR=954;PL=56,33;BL=30;LS=7;RB=400/255;SB=-/-;EN=PCMA;DE=PCMA;JI
=23,25;DL=43,43,44,IP=87.234.237.219:7078,62.225.244.101:9096

See here for more details https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/xrtpv32.pdf

**Comment by Sp0rN** [comment]
Thanks @negbie 

Ill look at applying this to freeswitch :)
