### ISSUE TITLE
New Installation -- No Data in Homer

### ISSUE THREAD

**Issue by lylepratt** [sipcapture/homer7-docker#67]
I've just installed Homer using docker. I am sending SIP data from OpenSIPs (a pretty old version) and I can see the SIP hit the box on port 9060, however no data seems to be being stored by Homer. I'm assuming I am missing something simple? I would appreciate any help!

Thanks!

**Comment by lmangani** [comment]
Welcome to the club. This could be caused by literally anything going wrong but as a starter and exclusing any network issue, make sure you're using HEPv3 from your OpenSIPS. 

In either case, you should see some logs from `heplify-server` compaining about parsing or inserting messages. The more logs/details, the better.

**Comment by lylepratt** [comment]
Thanks for the pointer. I'm using a pretty old version of OpenSIPS and I don't think it supports HEPv3. Do you know if theres any way to override that?

**Comment by lmangani** [comment]
You can switch off the integrated HEP agent and use `heplify` on the instance as long as you're not using it for TLS and you're good to go!

**Comment by lylepratt** [comment]
You mean use heplify on my opensips instances?

**Comment by lmangani** [comment]
@lylepratt that's just a suggestion to go passive and avoid touching them and unless they support HEPv3 or v2

**Comment by lylepratt** [comment]
They do support V2. Is there a way to get my homer7 install to accept HEP V2 instead of just V3? I'm fairly certain that is my issue because of logs like this:
`WARN malformed packet with length 659 which is neither hep nor protobuf encapsulated`

**Comment by lmangani** [comment]
`heplify-server` only supports HEPv3 nowadays so the only viable option is to use `heplify` as suggested here

**Comment by lylepratt** [comment]
Thanks for your help!
