### ISSUE TITLE
Tables not being created in postgres

### ISSUE THREAD

**Issue by nakchak** [sipcapture/homer7-docker#70]
Applogies if this is the wrong tracker for this issue, but i seem to have an issue with homer 7.7 docker install, but i dont know if its actually an issue with heplify-server.

**Issue**
Tables/partitions dont seem to get created in postgres, fillings logs with this:

`db                | 2020-04-15 12:37:30.256 UTC [225] ERROR:  no partition of relation "hep_proto_1_default" found for row'
'db                | 2020-04-15 12:37:30.256 UTC [225] DETAIL:  Partition key of the failing row contains (create_date) = (2020-04-15 12:37:26.609269+00).`
`db                | 2020-04-15 12:37:30.256 UTC [225] CONTEXT:  COPY hep_proto_1_default, line 1: "75acad854ad2620a4f2dc9142d5ab90  2020-04-15T12:37:26.609269Z     {"protocolFa..."`

If i restart heplify server `sudo docker-compose restart heplify-server` the tables seem to get created  and everything works for a day or so, then the same issue happens until i manually restart it again.

My install is literally the following:

1. Clone homer7-docker and checkout the 7.7 branch
2. Run `sudo docker-compose up -d`

Works fine for a week or so, then needs the heplify server restarted every day.

Am i missing something in my deployment or is a scheduled job failing?

**Comment by lmangani** [comment]
Thanks for the report. Could you link this to an issue on the `heplify-server` repository?

**Comment by lmangani** [comment]
@adubovikov @negbie any suggestions as if the current settings are wrong?

**Comment by adubovikov** [comment]
looks like the "homer_user" doesn't have permissions to create partitions. Can you please check/get the relations ?

**Comment by nakchak** [comment]
@adubovikov Noticed in the heplify-server log during start up some warnings relating to the homer_user and the postgres role not existing. Log attached
[heplify-server-startup.txt](https://github.com/sipcapture/homer7-docker/files/4482156/heplify-server-startup.txt)

Are there any pointers for getting more info that what is available from `docker-compose logs heplify-server` will happily document and add wiki entries for fault finding

**Comment by adubovikov** [comment]
no, it's ok, but only concern is about this:
```
heplify-server    | Could not find toml config file, use flag defaults. <nil>
```
@lmangani do we have config in the docker ?

**Comment by adubovikov** [comment]
@nakchak do you see any errors in the postgress's log ?

**Comment by nakchak** [comment]
@adubovikov nothing jumping out at me since i restarted, attached is the current contents of the log since i restarted this afternoon, will report back once a rotate has/hasn't happened.
[db-startup.txt](https://github.com/sipcapture/homer7-docker/files/4483494/db-startup.txt)

**Comment by negbie** [comment]
Tables should be rotated during night and you should see in the heplify-server log something like
finished rotate job next will run at ...
finished drop job next will run at ...

grep for these messages and check the postgres log in that timerange aswell.

**Comment by nakchak** [comment]
Nothing useful in the logs at all, seems it can go 48hours before it needs a restart

Attached are the logs i get, this is with a fresh clone of the homer7-docker repo checkedout to the 7.7 branch, and provisioned by `docker-compose up -d` no config or tweaking my end

[heplify-rotate-fail.txt](https://github.com/sipcapture/homer7-docker/files/4494697/heplify-rotate-fail.txt)

**Comment by negbie** [comment]
This does not help. So you did not find the string "finished rotate job next will run at"? If not the issue can be closed and you should enable the rotator with:

- "HEPLIFYSERVER_DBROTATE=true"

To debug the rotator you can set

- "HEPLIFYSERVER_LOGDBG=rotator"

**Comment by nakchak** [comment]
@negbie That was all there was in the logs, i disagree that it should be closed as this is something that should work out of the box with no user involvement with a docker install.  If i cant provision a working system using the minimal provided instructions then its pointless offering a containerised deployment option and i would be better off running a traditional scripted install and manually configuring everything, but again due to the lack of indepth deployment documentation and configuration values (that i can find anyway) that isnt much of an option.

Aside from my moaning about documentation (which i am happy to contribute towards by the way) homer 7.7 is proving to be a very frustrating release, stuff which has worked for months no longer does, and at the very least i should be able to expect the data capture side of things to be rock solid out of the box, i can look past graphical and analytical bells and whistles not working as long as i can rely on the data being there to requery once working....

**Comment by lmangani** [comment]
Hi @nakchak well things WOULD be solid out of the box if users contributed towards it instead of demand or expect things to be perfect without any effort. You might be the exception here since you're cooperating, but the project stability is only going to be as good as the community makes it by producing cooperative reports and actions. There is no "at the very least" and If you choose to use the containers, you also choose to test and help make them better - its a two way street and the frustration on this side for getting no contributions is surely greater than the one on the user front for getting no fancy documentation. I spent years producing the 5.x documentation alone and now I believe it should be community driven since we're focusing on the code and the difficult parts of the game already. If that doesn't sound fair, please express your views freely.

This said, @negbie provided a setting to try, so it would be best to comment on the effectiveness of that perhaps as next step. This has also been added to the containers.

**Comment by negbie** [comment]
I just saw that Lorenzo made some commits yesterday and added 
"HEPLIFYSERVER_DBROTATE=true"
to the docker-compose files. Normally this is the default as you can see here
https://github.com/sipcapture/heplify-server/blob/master/config/config.go#L35

So maybe there is some other issue? Let me explain a little bit the rotator...
If you like you can take a look at this function:
https://github.com/sipcapture/heplify-server/blob/master/rotator/rotator.go#L296

There is a cronjob for 0 30 03 * * * which will create every night data tables for the next 2 days and drop table which are older than dropdays and as you can see there will be this log line after each operation:

logp.Info("finished rotate job next will run at %v\n", time.Now().Add(time.Hour*24+1))
logp.Info("finished drop job next will run at %v\n", time.Now().Add(time.Hour*24+1))

Thats why I ask you to look for those messages as the maybe could give us a hint whats going wrong.

**Comment by lmangani** [comment]
@negbie i added the default to be more explicit for users since its causing confusion in general

**Comment by negbie** [comment]
Yeah I already thought you did this mostly for clarity and it's good to have this in place no matter if it's default or not.

**Comment by negbie** [comment]
@nakchak to proceed here I would suggest that you set
"HEPLIFYSERVER_LOGDBG=rotator"
and maybe reduce dbdropdays to 1 to maybe run earlier in the error condition.

**Comment by nakchak** [comment]
@lmangani I fully agree, lets get this fixed :), my issue is that i am a total novice when it comes to docker (this is the first deployment of any complexity i have played with, so i am total newb, but 20+ years system and network admin experience as well as dev and dba stuff so half my frustartion is finding where to change the settings i want to change :D), guess this gives me a chance to have a poke at go, its been on my list of languages to have a look at for a while...

@negbie i shall try those settings and report back

Forgive the newb question, but it is litterally a case of adding the values to the heplify-server secction of docker-compose.yaml and running `docker-compose up -d` afterwards to update the settings?

**Comment by negbie** [comment]
Exactly!

**Comment by lmangani** [comment]
@nakchak correct, check the latest PR which was exactly a display of this exercise to test with

**Comment by nakchak** [comment]
@lmangani @negbie Cheers guys, settings updated, i had already added the explicit DBROTATE option, but have added the logging one too

Can see a lot more useful messages relating to rotator now in the logs, following the recreation it looks like its sucessfully rotated the tables and created indices, now i guess wait until Monday as i seem to get 48hours of capture before the rotation fails.

FWIW i am fan of putting all config values into configs/scripts and just commenting them out if they are a default value as a soft touch form of documentation, in this case i would only include homer project associated values and links to the other projects wiki's, willl see what i can do after i have worked through the heplify-server source.

**Comment by nakchak** [comment]
Managed to find a bit of time to do some poking and learning...

I think the cron job is failing to create inside the heplify-server container, unless the cron functions in rotator.go dont use standard crontab....  

This is what i get when i run `docker exec -it heplify-server crontab -l`

`
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly
`

and a quick `ls -alR' through `/etc/periodic` yields nothing but empty directories.

One thing reading the code in question it seems like the cron functionality is passed in via the constructor (apologies if my terminology is off, have never looked at go before) but there seems to be no error capturing or logging related to its use, other than a couple of wrappers around calls to createTables(), does go have a try catch construct, if so it might be worth wrapping the calls to createJob in such a manner incase the issue is with cron creation/permissions, rather than the job logic it self.

**Comment by negbie** [comment]
It does not use os cronjobs ;)

**Comment by nakchak** [comment]
Thought as much seemed a bit fragile if it did.  Is there any way to verify its creation or is it purely in memory with the server daemon?

**Comment by nakchak** [comment]
@negbie is this the cron lib in use? https://godoc.org/github.com/robfig/cron

If so will try give go dev work a try and see if I can hack the logging pattern in the docs in, as well making the cron pattern a config value as it would be handy to specify a custom schedule to test this

Sorry if I'm pushy to get a fix going, just keen to give back where I can

**Comment by negbie** [comment]
@nakchak thanks for your effort and willingness to contribute back! Maybe it's not worth it to introduce two new flags (for cron drop and create time) and I don't think it's worth to use the logger interface of the used cron lib. All errors should be captured and printed already.

I just went over the code and refactored the drop function a bit. It was a contribution of a community member. I don't think it was affecting you because your issue is with table creation and not deletion.

So I think the best thing you can do is to watch the logs and report errors here.

**Comment by nakchak** [comment]
@negbie Unfortunatly the logs look identical to the previous fail log i posted, i.e. missing partition errors after 00:00:00 with no extra rotator info, attached is the full log since i upped the rotator logging  and recreated.

As far as i can tell the call to createTables() completes sucessfully, but it does look like the cron part is silently failing.  heplify-server is using version 1.20 of the cron lib from what i can see in the project files, but the docs for that version seem to have been replaced with the v3 docs and i cant find the older ones, either way i think to narrow down the problems i will need to add some logging to verify that the task is scheduled and or greater insight into the cron package.

[heplify-server-rotate-fail-2.log](https://github.com/sipcapture/homer7-docker/files/4502446/heplify-server-rotate-fail-2.log)

**Comment by negbie** [comment]
@nakchak thanks for the logs. Yes it's definitely the case that 
r.createJob.AddFunc
and
r.dropJob.AddFunc

silently failing. I added more logging around them in heplify-server 1.29 and upgraded the cron lib to v3. Just wait till the docker image is build and then please do a

docker-compose pull
docker-compose up -d

Make sure in the log that you are running version 1.29.

**Comment by negbie** [comment]
@nakchak I guess I know whats going on. Before heplify-server 1.28 I did not checked the error for the cronjob AddFunc

r.createJob.AddFunc("0 30 03 * * *", func()...
and since I used v1 of the lib you could call it with 6 cron time fields (0 30 03 * * *) the first one was for seconds.

Now the interesting part. In the rotator.go file the import path was
"github.com/robfig/cron"

Because I had v1 already in place that version was used. But as the maintainer of the lib did the switch to v3 a fresh go get will dowload v3.

So after manually switching to v3 and checking the error of AddFunc
_,err := r.createJob.AddFunc("0 30 03 * * *", func()...

I can see in the logs:
ERR expected exactly 5 fields, found 6: [0 30 03 * * *]

**Comment by negbie** [comment]
@nakchak thank you for mentioning that there is a new v3 version! This was the missing piece I guess which helped me to find and hopefully fix this fast.

The whole topic around versioned inport paths is currently a hot topic in the Go community. For example see here:
https://twitter.com/peterbourgon/status/1250799192894779392

**Comment by nakchak** [comment]
Excellent, i was starting to think the same but assumed 
https://github.com/sipcapture/heplify-server/blob/5a1846eebe7b3f81d7fdcc3b9899197de899c635/go.mod#L25
meant it was pulling in v1.20  but i guess it would need the tag in the uri as well 

Like i said my exposure to GO is measured in hours and yet to compile in anger so it all comes from a PseudoCode perspective to me lol.

I had noticed that latest version used cron format instead of quarts format cron strings, but assumed (fatal error on my part) go package refs worked like gems, npm, composer, nuget and apt/yum etc with a version specified being the version pulled

Glad to have helped, and will test as soon is as possible!

**Comment by nakchak** [comment]
`2020/04/21 03:30:00.029689 rotator.go:303: INFO run create job` 
verified sucessful rotation last night so closing issue, #350 looks to be same root cause so can probably be closed on assumption or i can change my dropdays to 1 to provide proof tomorrow?

Cheers Guys!

**Comment by negbie** [comment]
@nakchak glad to read this! Again, thanks for your help to debug this. Sometimes this is more valueable than plain code! Yes I think it can be closed too.

**Comment by systemcrash** [comment]
I also confirm this issue (it's probably been a lingering background issue for a while). 

```
db_1              | 2020-05-11T16:15:21.223670860Z 2020-05-11 16:15:21.223 UTC [39] ERROR:  no partition of relation "hep_proto_1_default" found for row
db_1              | 2020-05-11T16:15:21.223733068Z 2020-05-11 16:15:21.223 UTC [39] DETAIL:  Partition key of the failing row contains (create_date) = (2020-05-11 16:15:20.947463+00).
db_1              | 2020-05-11T16:15:21.223744125Z 2020-05-11 16:15:21.223 UTC [39] CONTEXT:  COPY hep_proto_1_default, line 1: "3bb72acb-bda5585cd1-4792258c@sipgt-6ce7448f	2020-05-11T16:15:20.947463Z	{"protocolFamily":2,"protoco..."
db_1              | 2020-05-11T16:15:21.223754022Z 2020-05-11 16:15:21.223 UTC [39] STATEMENT:  COPY hep_proto_1_default(sid,create_date,protocol_header,data_header,raw) FROM STDIN
db_1              | 2020-05-11T16:15:21.223766688Z 2020-05-11 16:15:21.223 UTC [42] ERROR:  no partition of relation "hep_proto_1_default" found for row
db_1              | 2020-05-11T16:15:21.223775392Z 2020-05-11 16:15:21.223 UTC [42] DETAIL:  Partition key of the failing row contains (create_date) = (2020-05-11 16:15:20.946787+00).
db_1              | 2020-05-11T16:15:21.223783500Z 2020-05-11 16:15:21.223 UTC [42] CONTEXT:  COPY hep_proto_1_default, line 1: "3bb72acb-bda5585cd1-4792258c@sipgt-6ce7448f	2020-05-11T16:15:20.946787Z	{"protocolFamily":2,"protoco..."
```


Is this the 'fix'?

> This does not help. So you did not find the string "finished rotate job next will run at"? If not the issue can be closed and you should enable the rotator with:
> 
>     * "HEPLIFYSERVER_DBROTATE=true"
> 
> 
> To debug the rotator you can set
> 
>     * "HEPLIFYSERVER_LOGDBG=rotator"

**Comment by systemcrash** [comment]
I restarted `heplify-server` and db logs printed this also...

```
db_1              | 2020-05-11T16:15:41.114074217Z 2020-05-11 16:15:41.113 UTC [6177] ERROR:  database "homer_data" already exists
db_1              | 2020-05-11T16:15:41.114107947Z 2020-05-11 16:15:41.113 UTC [6177] STATEMENT:  CREATE DATABASE homer_data
db_1              | 2020-05-11T16:15:41.114598994Z 2020-05-11 16:15:41.114 UTC [6177] ERROR:  role "homer_user" already exists
db_1              | 2020-05-11T16:15:41.114616684Z 2020-05-11 16:15:41.114 UTC [6177] STATEMENT:  CREATE USER homer_user WITH PASSWORD 'homer_password';
db_1              | 2020-05-11T16:15:41.114936681Z 2020-05-11 16:15:41.114 UTC [6177] ERROR:  role "postgres" does not exist
db_1              | 2020-05-11T16:15:41.114951838Z 2020-05-11 16:15:41.114 UTC [6177] STATEMENT:  GRANT postgres to homer_user;
db_1              | 2020-05-11T16:22:40.065489244Z 2020-05-11 16:22:40.065 UTC [8464] ERROR:  relation "hep_proto_100_registration" does not exist at character 15
db_1              | 2020-05-11T16:22:40.065563114Z 2020-05-11 16:22:40.065 UTC [8464] STATEMENT:  SELECT * FROM "hep_proto_100_registration"  WHERE (sid in ($1) and create_date between $2 and $3)
db_1              | 2020-05-11T16:22:40.066783315Z 2020-05-11 16:22:40.066 UTC [8464] ERROR:  relation "hep_proto_5_registration" does not exist at character 15
db_1              | 2020-05-11T16:22:40.066817099Z 2020-05-11 16:22:40.066 UTC [8464] STATEMENT:  SELECT * FROM "hep_proto_5_registration"  WHERE (sid in ($1) and create_date between $2 and $3)
```
