### ISSUE TITLE
Tab SIP flow Issue (Flow & Export & Messages)

### ISSUE THREAD

**Issue by benhamoua** [sipcapture/homer7-docker#72]
Hi, 
Running Hom7-prom-all on docker: today i make pull request but it seems an issue appear when displaying SIP flow (there is no Tab message & Flow & Export like befor), i can see sip message captured but can't display the flow or export it

![image](https://user-images.githubusercontent.com/57920841/79670497-687b4d00-81bb-11ea-9ed7-b71cad0cbb71.png)

![image](https://user-images.githubusercontent.com/57920841/79670569-f7886500-81bb-11ea-8f44-35dd6071fa28.png)

**Comment by adubovikov** [comment]
do you see any errors in the web console ? (F12)  What UI version do you have ?

**Comment by benhamoua** [comment]
i'm using homer 7.7.032(prod)

![image](https://user-images.githubusercontent.com/57920841/79699137-641b6680-8285-11ea-9524-87e3903c3fac.png)

**Comment by adubovikov** [comment]
Please click on "Session ID" and after check the web console

**Comment by benhamoua** [comment]
![image](https://user-images.githubusercontent.com/57920841/79701733-5838a000-8297-11ea-9917-8ac1f1828e19.png)

**Comment by benhamoua** [comment]
below we can see all call flow: "same call ID"

![image](https://user-images.githubusercontent.com/57920841/79702062-d6964180-8299-11ea-865f-71f9a62de17a.png)

i have try to click one by one the "Call ID", i found that some of them is displaying the Flow Tab, and the other not.

![image](https://user-images.githubusercontent.com/57920841/79702312-e4e55d00-829b-11ea-8e7a-b8250878cd01.png)

![image](https://user-images.githubusercontent.com/57920841/79702350-2f66d980-829c-11ea-8806-fef1c2467b2a.png)

**Comment by adubovikov** [comment]
it has been fixed. Please pull the latest image

**Comment by benhamoua** [comment]
I confirme, thank you.
