### ISSUE TITLE
Cant get changes to loki-local-config.yaml to take effect inside of container

### ISSUE THREAD

**Issue by nakchak** [sipcapture/homer7-docker#74]
Attempting to fix #73 
I have hit a roadblock/limit of my knowledge with docker.  

I have changed the syntax of the duration parameters but cant seem to get them to apply to the container, i have also intentionally malformed the yaml file to trigger a different parse error to verify the config is being honoured and again no indication that its being applied to my container.

I have tried the following commands with no luck, am i doing something wrong?

1. `docker-compose up -d`
2. `docker-compose down
docker-compose up -d`
3. `docker-compose --verbose up --force-recreate --build`

**Comment by cerienj** [comment]
you need to add
    volumes:
      - ./loki/loki-local-config.yaml:/etc/loki/local-config.yaml
in the loki service definition section of hte file
homer7-docker/heplify-server/hom7-prom-all/docker-compose.yml
(in my case, line 100)

**Comment by nakchak** [comment]
@cerienj thanks, thats done the trick, loki now loads, and stays up but heplify server is now in a restart cycle...
