### ISSUE TITLE
Default Admin Authentication

### ISSUE THREAD

**Issue by TheBeachMaster** [sipcapture/homer7-docker#8]
The default Admin authentication : 
 `user: admin` 
  `password: sipcature` 

Fails with `Email and password combination not recognised` error. 

![screenshot from 2019-01-08 13-49-58](https://user-images.githubusercontent.com/9129843/50826419-a482f980-134c-11e9-83bd-53183b357a05.png)

This seem to affect Homer7 deployments.  
 
Screenshot captures `homer7-docker/hepop/hom7-json-influx` instance

UPDATE: 

This is the Docker deployments seems to be related to [this guy](https://github.com/sipcapture/homer/issues/120)

**Comment by lmangani** [comment]
Hi @TheBeachMaster that login is from HOMER 5 so I'm a little confused.... could you doublecheck?

**Comment by TheBeachMaster** [comment]
My bad @lmangani , seems my Homer5 session had been cached....

Logged in successfully.

My bad :man_facepalming:   
 
Closing...
