### ISSUE TITLE
Purging data on a regular basis?

### ISSUE THREAD

**Issue by lukeescude** [sipcapture/homer7-docker#85]
Hello, is it possible to set up some kind of weekly/nightly purge?

I had 100% of my host's hard disk fill up with SIP packets. I figured homer7 would have had some kind of cleanup capabilities built-in.

**Comment by adubovikov** [comment]
Here you are:
https://github.com/sipcapture/heplify-server/blob/master/example/homer7_config/heplify-server.toml#L31-L35

**Comment by adubovikov** [comment]
the hepliy-server will run an internal crontjob that will drop your old partition

**Comment by lukeescude** [comment]
Hmm I have added the the following to the docker-compose file:

      - "HEPLIFYSERVER_DBDROPDAYS=3"
      - "HEPLIFYSERVER_DISCARDMETHOD=[OPTIONS]"

And it does not appear to be working after restarting - OPTIONS packets still show up. Is there a particular location this config needs to go?

**Comment by lmangani** [comment]
try adding this:
```
DBDropOnStart         = true
```

**Comment by lukeescude** [comment]
I will give that a try!

Out of curiosity, whenever Homer restarts, most of my Kamailio proxies must be restarted in order to start sending HEP again... it’s like kamailio doesn’t automatically reconnect to Homer. Is this an issue on the kamailio side or homer side?

It has happened with Kamailio 4.x and 5.x with Homer 5.x and 7.x all combinations.

**Comment by adubovikov** [comment]
no, it should send traffic without restart, this is UDP and kamailio uses"sendto" function that doesn't require connect

**Comment by lukeescude** [comment]
Strange, I wonder why I must restart kamailio then... I will experiment with that and see if I can find out why.

**Comment by lukeescude** [comment]
The HDD is still filling up - I have data lasting 7+ days even though I've set HEPLIFYSERVER_DBDROPDAYS=3 in the configuration.

Is there a different place to put that, besides the docker-compose file?

**Comment by lmangani** [comment]
Could you confirm the heplify-server version from within the container please?

**Comment by lukeescude** [comment]
Hmmm, how do I do that?

**Comment by lmangani** [comment]
try pulling the latest container and see if it updates. `docker pull sipcapture/heplify-server:master`

**Comment by lukeescude** [comment]
Will do - I will perform this task later in the day, since I do not want to interrupt homer during the work day.

Thank you!

**Comment by lukeescude** [comment]
Hello, it does not appear like the new image helps at all - HDD still at 75% utilization, same as before the new image went up with docker-compose up -d

Any other tests?

**Comment by lukeescude** [comment]
It is interesting... Every time I restart the heplify-server, Grafana logs a large influx of packets.

See attached.
<img width="1094" alt="Screen Shot 2020-07-28 at 11 03 15 AM" src="https://user-images.githubusercontent.com/11986333/88683643-08514c80-d0c2-11ea-867b-e5c7da5c6984.png">

**Comment by lukeescude** [comment]
Interestingly, having the following doesn't function either:

  - 'HEPLIFYSERVER_DISCARDMETHOD=["OPTIONS"]'

Heplify still continues to log OPTIONS packets instead of discarding them. At least, they show up in Grafana.

**Comment by adubovikov** [comment]
Granfa makes stats, but this option doesn't write OPTIONS message into PostgressDB

**Comment by lukeescude** [comment]
In that case, these options might be working perfectly fine.

I will let it go for a few days and report back if necessary.

**Comment by lukeescude** [comment]
Well, I stand corrected - There are still OPTIONS packets showing up in the Homer search screens.

I believe the docker-compose file options are being ignored when heplify boots up.
