### ISSUE TITLE
How is retention handled

### ISSUE THREAD

**Issue by VeselaHouba** [sipcapture/homer7-docker#88]
Did I miss something obvious? I haven't found any rotation config or similar. I've just started `hom7-prom-all` bundle and I can see tables like this for multiple proto numbers:
```
 public | hep_proto_5_default                    | table | root
 public | hep_proto_5_default_20200913_0000      | table | root
 public | hep_proto_5_default_20200913_0600      | table | root
 public | hep_proto_5_default_20200913_1200      | table | root
 public | hep_proto_5_default_20200913_1800      | table | root
 public | hep_proto_5_default_20200914_0000      | table | root
 public | hep_proto_5_default_20200914_0600      | table | root
 public | hep_proto_5_default_20200914_1200      | table | root
 public | hep_proto_5_default_20200914_1800      | table | root
 public | hep_proto_5_default_20200915_0000      | table | root
 public | hep_proto_5_default_20200915_0600      | table | root
 public | hep_proto_5_default_20200915_1200      | table | root
 public | hep_proto_5_default_20200915_1800      | table | root
```

Am I supposed to drop them manually? If so, can you just state it somewhere in Readme? Thanks for answers :)

**Comment by lmangani** [comment]
Hi @VeselaHouba the setting for data rotation are within the `heplify-server` settings which can be controlled via ENV variables
```
DBRotate              = true
DBDropDays            = 7
DBDropDaysCall        = 7
DBDropDaysRegister    = 7
DBDropDaysDefault     = 7
DBDropOnStart         = false
```

As you can see, you can differentiate between different table/partition types, to keep calls longer than registrations, etc.

I hope this helps!

**Comment by VeselaHouba** [comment]
I don't know how I missed that. Thanks a lot.

**Comment by adubovikov** [comment]
@VeselaHouba sometimes it happens. Please star our project :-) https://github.com/sipcapture/homer/stargazers
