### ISSUE TITLE
LDAP and Lua with docker images

### ISSUE THREAD

**Issue by nakchak** [sipcapture/homer7-docker#90]
I have just got ldap and lua working on my dev deployment using the docker scripts.
I did this by hacking extra volumes into the docker compose file, to inject the lua script folder to heplify server, and the webapp_config.json file into homer-webapp (overwriting the containers supplied config).  Is this the best way to acheive this?
If not what is recommended?

Otherwise should i bundle my changes into a PR for a dev/hackers/tweakers version of the scripts?  As Lua support is great feature and has made homer 1000% more usable being able to query on some custom X-* headers.  Whilst not being able to easily tweak deployed web config to the webapp using the stock containers is a bit of a pain if you want ldap for example, as the docker entrypoint scripts dont currently have the ability to set ldap env vars as far as i can tell (plus i like having direct access to config files on my dev stack)

**Comment by lmangani** [comment]
Hi Tim,
Thanks for sharing your status with us, it definitely helps to understand the new challenges this feaure brings on the table - much appreciated!

As far as the Docker containers are involved, those are a baseline and not a complete solution, so mapping your own config files (generated or else) is the intended way, but we can and want to improve by better understanding the nature of those required changes to either consider making them defaults for all users or ease the process with examples, etc.

Could you share the PR so we can filter everything that's common scope, as well as use as reference?
