### ISSUE TITLE
Error in webapp frontend

### ISSUE THREAD

**Issue by ghettovoice** [sipcapture/homer7-docker#91]
Hello,
I have a problem with a fresh installation from the scratch with `docker-compose up -d`.

<img width="1680" alt="Снимок экрана 2020-10-13 в 13 08 36" src="https://user-images.githubusercontent.com/4323000/95847486-6ef71580-0d55-11eb-8992-c3d790aef045.png">

I got this error on a start webapp page after full reinstall with those commands:
```
docker-compose down
docker system prune --all --prune
docker-compose up -d
```

First time install was fully successful, no any errors.
I'm doing this on the latest `master` commit.

Thanks for the great tools!

**Comment by lmangani** [comment]
Thanks for the report! I can definitely reproduce this, so I expect to have a fix shortly.

**Comment by lmangani** [comment]
Pushed a new version and container builds to address this - could you kindly pull, check and confirm?

**Comment by ghettovoice** [comment]
Yes, now it works like a charm

**Comment by lmangani** [comment]
Wonderful! Thanks again for bringing this up, and feel free to reopen this issue in case of further complications.
