### ISSUE TITLE
Help with Grafana custom graphs - PROMTARGETIP and PROMTARGETNAME

### ISSUE THREAD

**Issue by solarmon** [sipcapture/homer7-docker#92]
Hi,

I'm having trouble understanding and finding information on how to customise the Grafana graphs.

Have it all working with the default Homer dashboard and widgets. However, I would like to customise it to show the graphs on a per SBC basis.

From what I can understand I need to set PROMTARGETIP and PROMTARGETNAME to define the various SBCs. However, I'm unsure as to what the IP address should be of - is it the IP of the source of the HEP packets coming from the SBC, or what?

I have ammended the docker-compose.yml file for the HEPLIFYSERVER_PROMTARGETIP and HEPLIFYSERVER_PROMTARGETNAME environment variables and have updated the build with a 'docker-compose up -d'

What do I now need to do with Homer/Grafana/Prometheus/ in order to be able to customise the graphs to show the stats on a per SBC basis. Any tips and pointers would be greatly appreciated.

Thank you!

**Comment by solarmon** [comment]
To answer my own question...

The PROMTARGETIP is the source IP in the SIP packet being captured by HEP (not the source IP of the HEP packet itself).

In Grafana, you can then use the 'interface_name' drop-down menu of the dashboard to filter by hostname(s).

**Comment by lmangani** [comment]
@solarmon that's indeed, correct!
