### ISSUE TITLE
ubuntu 20 LTS problem. caddy eternal restart.

### ISSUE THREAD

**Issue by dias3000** [sipcapture/homer7-docker#94]
**ubuntu 20 lts (fresh install, updated)**
Description:	Ubuntu 20.04.1 LTS
Codename:	focal

**docker (latest stable)**
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:58 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:52 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**hom7-prom-all (master)**

after **docker-compose up -d** caddy container wont ever started, with **docker ps** status "Restarting":
75f0421065e5   stefanprodan/caddy                 "/sbin/tini -- caddy…"   2 hours ago   Restarting (2) 51 seconds ago                                                              caddy

**docker logs caddy**:
goroutine 1 [running]:
github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
	src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc4200402c0, 0xc420037f50)
	src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
	src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
github.com/mholt/caddy/caddy/caddymain.init()
	<autogenerated>:1 +0x75
main.init()
	<autogenerated>:1 +0x44
panic: runtime error: slice bounds out of range

on **ubuntu 18 lts** with same docker and homer7 it works fine
Description:	Ubuntu 18.04.5 LTS
Codename:	bionic

92cccebc1d53   stefanprodan/caddy                 "/sbin/tini -- caddy…"   33 minutes ago   Up 51 seconds             0.0.0.0:3000->3000/tcp, 0.0.0.0:9080->9080/tcp, 0.0.0.0:9090->9090/tcp, 0.0.0.0:9093->9093/tcp   caddy

**Comment by lmangani** [comment]
could you perform a `docker-compose pull` inside the folder to make sure you have the latest version already?

**Comment by dias3000** [comment]
**docker-compose pull**
Pulling prometheus     ... done
Pulling nodeexporter   ... done
Pulling grafana        ... done
Pulling alertmanager   ... done
Pulling loki           ... done
Pulling caddy          ... done
Pulling db             ... done
Pulling homer-webapp   ... done
Pulling heplify-server ... done

**docker-compose up -d**
Creating prometheus ... done
Creating loki         ... done
Creating caddy        ... done
Creating grafana      ... done
Creating nodeexporter ... done
Creating db           ... done
Creating alertmanager   ... done
Creating heplify-server ... done
Creating homer-webapp   ... done

**docker ps**
abf27f246846   stefanprodan/caddy                 "/sbin/tini -- caddy…"   2 minutes ago   Restarting (2) 12 seconds ago                                                              caddy

**Comment by lmangani** [comment]
Upon review, I've decided to remove caddy from the stack. We used it when Grafana was hard to authenticate, but it seems now just a useless accessory users can add back if and when desired.

Could you please pull the latest compose and try again?

**Comment by dias3000** [comment]
> Could you please pull the latest compose and try again?

it works, thanks.
