### ISSUE TITLE
Non-GUI way of adding aliases in homer 7

### ISSUE THREAD

**Issue by devBash99** [sipcapture/homer7-docker#96]
I wanted to ask if there is any working way to add aliases in homer without using GUI. I tried adding the aliases directly in the database. These are the columns in which I added the data.  
alias | ip | port | mask  | status 
They showed in the UI but I was not able to modify or delete these values. It display and error in a pop-up saying "Not Found" when ever I try to do so.

**Comment by devBash99** [comment]
Not adding uuid's was the issue, I added the aliases using a script I made which generates unique uuids and inserted in to database. Now i can edit the values from the UI.
 Also does captureID need to ne unique. Can anyone tell me what it does?

**Comment by lmangani** [comment]
Note: This is NOT an issue with docker, and should be discussed in the main sipcapture/homer repository to get attention.
