### ISSUE TITLE
homer-app - issue with displaying grafana metrics via widget 

### ISSUE THREAD

**Issue by mikemeehan203** [sipcapture/homer7-docker#97]
When using a vanilla hom7-prom-all build I cannot get any grafana metrics to appear in the homer dashboard.  Below are the steps I'm taking.  Thanks.

(1) Update the host address, using an IP, instead of "grafana"

![01](https://user-images.githubusercontent.com/78174901/106765696-1353df00-6607-11eb-9b69-7dde7fa92453.png)

(2) Add a new dashboard

![02](https://user-images.githubusercontent.com/78174901/106765634-01723c00-6607-11eb-8cef-3a8cbdabe9bf.png)
![03](https://user-images.githubusercontent.com/78174901/106765667-0b943a80-6607-11eb-806d-25273d897a63.png)

(3) Add a grafana metrics widget

![04](https://user-images.githubusercontent.com/78174901/106765749-24045500-6607-11eb-944c-294e5893c3d9.png)

(4) Select the dashboard and panel **the fact that I can select the dashboard and panel tells me the communication between homer-app and grafana exists.

![05](https://user-images.githubusercontent.com/78174901/106765915-50b86c80-6607-11eb-92f0-61c341f582f7.png)
![06](https://user-images.githubusercontent.com/78174901/106765957-5f068880-6607-11eb-856a-dc84a47cf94a.png)

(5) The widget fails to successfully talk to the grafana instance.

![07](https://user-images.githubusercontent.com/78174901/106766101-852c2880-6607-11eb-94e4-ac46632996fc.png)

(6) That same dashboard can successfully be viewed when logging into grafana

![08](https://user-images.githubusercontent.com/78174901/106766372-cf150e80-6607-11eb-8413-e6007c999645.png)

Please let me know if you need anything else to help troubleshoot the issue.  Thank you in advance.

**Comment by lmangani** [comment]
Hello @mikemeehan203 this is a network issue - could you check what the network tab of your browser reports and which URL its trying to load?

![image](https://user-images.githubusercontent.com/1423657/106768155-f08fed80-663b-11eb-8023-ebf744ce1960.png)

**Comment by mikemeehan203** [comment]
Hi @lmangani, yes, here's what I've got -

![Initiator](https://user-images.githubusercontent.com/78174901/106772390-f53dad00-660d-11eb-910a-45d813244f41.png)

![Info](https://user-images.githubusercontent.com/78174901/106773874-8bbe9e00-660f-11eb-9384-7bc58550db06.png)

![chrome_01](https://user-images.githubusercontent.com/78174901/106772330-e5be6400-660d-11eb-8dd6-b10d01c7512c.png)

![chrome_02](https://user-images.githubusercontent.com/78174901/106772406-fa026100-660d-11eb-9fed-c5d0659ce68a.png)

It's worth noting, that this is a remote system I am access on the Internet, I'm not running it on my laptop.  When port forwarding to the above URL's (firewall access to port 3000 is not open from my laptop) I can see the intended graphs being requested, albeit I have no call volume at the moment.

![port_forward_attempt_1](https://user-images.githubusercontent.com/78174901/106772759-536a9000-660e-11eb-85f2-ba508c65a042.png)
![port_forward_attempt_2](https://user-images.githubusercontent.com/78174901/106772773-56658080-660e-11eb-96a5-9ee3219d3344.png)

Thanks,
Mike

**Comment by mikemeehan203** [comment]
Hi @lmangani,

I'm using an API access token from grafana.  As a test to make sure access is granted, if I were to change that access token to something invalid, the dashboards loaded into Grafana would not populate.  See (4).

Thanks,
Mike

**Comment by lmangani** [comment]
@AlexeyOplachko do you see anything out of the ordinary here?

**Comment by AlexeyOplachko** [comment]
This problem used to happen if you had UI on localhost and API on remote, but from what I've checked rn it isn't happening after we switched our approach to Grafana widget.

**Comment by lmangani** [comment]
@mikemeehan203 please describe step by step how you are configuring the widget from scratch. let's see where it happens.

**Comment by kvrudenko** [comment]
The same problem. In homer-webapp container I have this message:
`{"time":"2021-07-25T00:33:17.267260218+03:00","level":"ERROR","prefix":"echo","file":"proxy_1_11.go","line":"20","message":"remote http://grafana/ unreachable, could not forward: dial tcp 172.18.0.3:80: connect: connection refused"}`
Why app tries connect to port 80 ? Grafana published on port 3000 and the settings the same as @mikemeehan203 showed.

**Comment by kvrudenko** [comment]
Гомер нормально в виджете видит все дашборды в графане, развёрнутой в соседнем контейнере, но почему-то запрос на отображение делает не на тот порт, который указан в конфиге виджета.

**Comment by McSimDP** [comment]
Same problem.
In Chrome console: "Refused to display 'http://10.10.0.9:3000/' in a frame because it set **'X-Frame-Options' to 'deny'**."

**Comment by lmangani** [comment]
@McSimDP easy to google this up and see its not related to our project: 

https://grafana.com/docs/grafana/v7.5/administration/configuration/#allow_embedding

**Comment by McSimDP** [comment]
> @McSimDP easy to google this up and see its not related to our project:
> 
> https://grafana.com/docs/grafana/v7.5/administration/configuration/#allow_embedding

Thanks, helped
